### ISSUE TITLE
cmd/govim: gofumpt/gofumports configuration possibility

### ISSUE THREAD

**Issue by jbpratt** [govim/govim#1004]
I'm wondering about integrating [`gofumpt`](https://github.com/mvdan/gofumpt) into `govim`, as mentioned by @leitzler in Slack, there may not be a setting currently exposed to do this. 

### What version of Vim/Gvim are you using?

<details><summary>Vim/Gvim version</summary><br><pre>
$ vim --version
VIM - Vi IMproved 8.2 (2019 Dec 12, compiled Nov 15 2020 16:46:37)
</pre></details>

### What version of Go are you using (`go version`)?

<pre>
$ go version
go version go1.15.6 linux/amd64
</pre>

### What operating system and processor architecture are you using (`go env`)?

<details><summary><code>go env</code> Output</summary><br><pre>
$ go env
GOARCH="amd64"
GOOS="linux"
</pre></details>

### What version/commit of `govim` are you using?
0d0e56d

**Comment by myitcv** [comment]
@leitzler @mvdan  - has `gofumpt` been integrated with `gopls` yet?

**Comment by leitzler** [comment]
Yes, we should only need to expose the setting.

**Comment by myitcv** [comment]
Thanks for keeping up to date with where things are with `gopls` 💯 , @leitzler!

**Comment by jbpratt** [comment]
I think [this](https://github.com/golang/tools/blob/master/gopls/doc/vim.md#govim) can then get an update/fleshed out as this gets closed!
