### ISSUE TITLE
Errors after using :vim search command

### ISSUE THREAD

**Issue by theclapp** [govim/govim#1008]
### What version of Vim/Gvim are you using?

<details><summary>Vim/Gvim version</summary><br><pre>
$ vim --version
VIM - Vi IMproved 8.2 (2019 Dec 12, compiled Dec 12 2020 05:55:56)
macOS version
Included patches: 1-2127
Compiled by root@Traviss-Mac.local
Huge version with MacVim GUI.  Features included (+) or not (-):
+acl               +file_in_path      -mouse_sysmouse    -tag_old_static
+arabic            +find_in_path      +mouse_urxvt       -tag_any_white
+autocmd           +float             +mouse_xterm       -tcl
+autochdir         +folding           +multi_byte        +termguicolors
-autoservername    -footer            +multi_lang        +terminal
+balloon_eval      +fork()            -mzscheme          +terminfo
+balloon_eval_term +fullscreen        +netbeans_intg     +termresponse
+browse            +gettext           +num64             +textobjects
++builtin_terms    -hangul_input      +odbeditor         +textprop
+byte_offset       +iconv             +packages          +timers
+channel           +insert_expand     +path_extra        +title
+cindent           +ipv6              +perl/dyn          +toolbar
+clientserver      +job               +persistent_undo   +transparency
+clipboard         +jumplist          +popupwin          +user_commands
+cmdline_compl     +keymap            +postscript        +vartabs
+cmdline_hist      +lambda            +printer           +vertsplit
+cmdline_info      +langmap           +profile           +virtualedit
+comments          +libcall           +python/dyn        +visual
+conceal           +linebreak         +python3/dyn       +visualextra
+cryptv            +lispindent        +quickfix          +viminfo
+cscope            +listcmds          +reltime           +vreplace
+cursorbind        +localmap          +rightleft         +wildignore
+cursorshape       +lua/dyn           +ruby/dyn          +wildmenu
+dialog_con_gui    +menu              +scrollbind        +windows
+diff              +mksession         +signs             +writebackup
+digraphs          +modify_fname      +smartindent       -X11
+dnd               +mouse             -sound             -xfontset
-ebcdic            +mouseshape        +spell             +xim
+emacs_tags        +mouse_dec         +startuptime       -xpm
+eval              -mouse_gpm         +statusline        -xsmp
+ex_extra          -mouse_jsbterm     -sun_workshop      -xterm_clipboard
+extra_search      +mouse_netterm     +syntax            -xterm_save
-farsi             +mouse_sgr         +tag_binary
   system vimrc file: "$VIM/vimrc"
     user vimrc file: "$HOME/.vimrc"
 2nd user vimrc file: "~/.vim/vimrc"
      user exrc file: "$HOME/.exrc"
  system gvimrc file: "$VIM/gvimrc"
    user gvimrc file: "$HOME/.gvimrc"
2nd user gvimrc file: "~/.vim/gvimrc"
       defaults file: "$VIMRUNTIME/defaults.vim"
    system menu file: "$VIMRUNTIME/menu.vim"
  fall-back for $VIM: "/Applications/MacVim.app/Contents/Resources/vim"
Compilation: clang -c -I. -Iproto -DHAVE_CONFIG_H -DFEAT_GUI_MACVIM -Wall -Wno-unknown-pragmas -pipe  -DMACOS_X -DMACOS_X_DARWIN  -g -O2 -arch x86_64 -U_FORTIFY_SOURCE -D_FORTIFY_SOURCE=1 -Wall -Wex
tra -Wshadow -Werror -Wno-error=missing-field-initializers -Wno-error=deprecated-declarations -Wno-error=unused-function
Linking: clang   -L. -fstack-protector-strong -L/usr/local/lib -L/usr/local/opt/libyaml/lib -L/usr/local/opt/openssl@1.1/lib -L/usr/local/opt/readline/lib -L. -fstack-protector-strong -L/usr/local/l
ib -L/usr/local/opt/libyaml/lib -L/usr/local/opt/openssl@1.1/lib -L/usr/local/opt/readline/lib  -arch x86_64 -L/usr/local/lib -o Vim -framework Cocoa -framework Carbon       -lm  -lncurses -liconv /
usr/local/lib/libintl.a -framework AppKit   -fstack-protector  -L/System/Library/Perl/5.18/darwin-thread-multi-2level/CORE
</pre></details>

### What version of Go are you using (`go version`)?

<pre>
$ go version
go version go1.15 darwin/amd64

</pre>

### What operating system and processor architecture are you using (`go env`)?

<details><summary><code>go env</code> Output</summary><br><pre>
$ go env
GO111MODULE=""
GOARCH="amd64"
GOBIN=""
GOCACHE="/Users/lclapp/Library/Caches/go-build"
GOENV="/Users/lclapp/Library/Application Support/go/env"
GOEXE=""
GOFLAGS=""
GOHOSTARCH="amd64"
GOHOSTOS="darwin"
GOINSECURE=""
GOMODCACHE="/Users/lclapp/src/gopath/pkg/mod"
GONOPROXY=""
GONOSUMDB=""
GOOS="darwin"
GOPATH="/Users/lclapp/src/gopath"
GOPRIVATE=""
GOPROXY="https://proxy.golang.org,direct"
GOROOT="/usr/local/go"
GOSUMDB="sum.golang.org"
GOTMPDIR=""
GOTOOLDIR="/usr/local/go/pkg/tool/darwin_amd64"
GCCGO="gccgo"
AR="ar"
CC="clang"
CXX="clang++"
CGO_ENABLED="1"
GOMOD=""
CGO_CFLAGS="-g -O2"
CGO_CPPFLAGS=""
CGO_CXXFLAGS="-g -O2"
CGO_FFLAGS="-g -O2"
CGO_LDFLAGS="-g -O2"
PKG_CONFIG="pkg-config"
GOGCCFLAGS="-fPIC -m64 -pthread -fno-caret-diagnostics -Qunused-arguments -fmessage-length=0 -fdebug-prefix-map=/var/folders/39/_r1_10h95r58mp5sy4qysw9r0000gn/T/go-build279271434=/tmp/go-build -gno-
record-gcc-switches -fno-common"
</pre></details>

### What version/commit of `govim` are you using?

```
% commit 563f0b213648891221cf88e44753b3f1187c2158 (HEAD -> main, origin/main, origin/HEAD)
Author: Pontus Leitzler <leitzler@users.noreply.github.com>
Date:   Tue Dec 15 21:00:25 2020 +0100
```

### What is the output of `:messages` in Vim?

```
Error detected while processing BufRead Autocommands for "*.go"..function <SNR>16_callbackAutoCommand[18]..<SNR>16_ch_evalexpr[11]..BufRead Autocommands for "*.go"..function <SNR>16_callbackAutoCommand[18]..<SNR>16_ch_evalexpr:
line   11:
E605: Exception not caught: got error whilst handling autocommand:1: driver error: ChannelCall("s:batchCall") failed: failed to call s:batchCall([[[call [s:mustNoError []] prop_remove {0 42 1}] [call [s:mustNoError []] prop_remove {0 1 1}] [call [s:mustNoError []] prop_remove {0 90 1}] [call [s:mustNoError []] prop_remove {0 91 1}]]]) in Vim: Caught 'failed to call prop_remove([{''id'': 0, ''all'': 1, ''bufnr'': 91}]): Vim(let):E158: Invalid buffer name: 91' in BufRead Autocommands for "*.go"..function <SNR>16_callbackAutoCommand[18]..<SNR>16_ch_evalexpr[9]..<SNR>16_define[53]..<SNR>16_batchCall, line 35
```

Note that it's referencing buffer 91 and I don't actually have 91 buffers loaded.

### Do the Vim channel, `govim` or `gopls` log files show anything interesting?

Dude I have no idea.

### How did you install `govim`?

Initial via vim-plug, I think.  More recently via something along the lines of

```sh
cd ~/.vim/plugged/govim
git co main
git pull
go install -v -x ./...
```

and

```sh
go get -v golang.org/x/tools/gopls@latest
```

### What did you do?

cd to the root directory of a Go project, e.g. `~/.vim/plugged/govim`
edit a Go file in mvim (aka gvim) / MacVim GUI
`:vim /somepattern/ **/*.go`

### What did you expect to see?

The output of the `:vim` search

### What did you see instead?

The above-mentioned errors.

After that, sometimes I get errors like this about 2s after I move the cursor (I have updatetime=2000), including in non-Go files:

```
Error detected while processing CursorHold Autocommands for "*"..function <SNR>16_userBusy[3]..GOVIM_internal_SetUserBusy[2]..<SNR>16_callbackFunction[2]..<SNR>16_ch_evalexpr[11]..CursorHold Autocommands for "*"..function <SNR>16_userBusy[3]..GOVIM_internal_SetUserBusy[2]..<SNR>16_callbackFunction[2]..<SNR>16_ch_evalexpr:
line   11:
E605: Exception not caught: got error whilst handling GOVIM_internal_SetUserBusy: driver error: ChannelCall("s:batchCall") failed: failed to call s:batchCall([[[call [s:mustNoError []] prop_remove {0 85 1}] [call [s:mustNoError []] prop_remove {0 93 1}] [call [s:mustNoError []] prop_remove {0 1 1}]]]) in Vim: Caught 'failed to call prop_remove([{''id'': 0, ''all'': 1, ''bufnr'': 93}]): Vim(let):E158: Invalid buffer name: 93' in CursorHold Autocommands for "*"..function <SNR>16_userBusy[3]..GOVIM_internal_SetUserBusy[2]..<SNR>16_callbackFunction[2]..<SNR>16_ch_evalexpr[9]..<SNR>16_define[53]..<SNR>16_batchCall, line 35
```

and here it's referencing buffer 93 and again I don't actually have 93 buffers loaded.

**Comment by leitzler** [comment]
Try upgrading vim to (at least) 8.2.2185, it should be fixed there!

**Comment by theclapp** [comment]
I downloaded MacVim master, which is not (yet) current with core Vim, and made the change mentioned in https://github.com/vim/vim/pull/7518 manually, and that does seem to have fixed this error.  Thanks!
