### ISSUE TITLE
cmd/govim: delete internal buffers on BufWipeout autocommands

### ISSUE THREAD

**Issue by leitzler** [govim/govim#1033]
### What version/commit of `govim` are you using?
Current main, 9b702de

Currently we are listening for `BufDelete` and clean up our internal state when we get it, but the help file states that we won't get it for buffers that is deleted and not loaded:

> Before deleting a buffer from the buffer list.
> The BufUnload may be called first (if the
> buffer was loaded).
> Also used just before a buffer in the buffer
> list is renamed.

We should do the same thing when we get a `BufWipeout` autocommand to make sure we don't keep things in memory that aren't in vim anymore. From `BufWipeout`:

> Before completely deleting a buffer.  The
> BufUnload and BufDelete events may be called
> first (if the buffer was loaded and was in the
> buffer list).  Also used just before a buffer
> is renamed (also when it's not in the buffer
> list).

**Comment by myitcv** [comment]
The dreaded Vim buffer state lifecycle strikes again :)
