### ISSUE TITLE
Passing configuration to gopls

### ISSUE THREAD

**Issue by a-palchikov** [govim/govim#1049]
Sorry if this has been already answered (would appreciate any further pointers).

### What version of Vim/Gvim are you using?

<details><summary>Vim/Gvim version</summary><br><pre>
$ vim --version
Vi IMproved 8.2
</pre></details>

### What version of Go are you using (`go version`)?

<pre>
$ go version
go 1.15.6
</pre>

### What operating system and processor architecture are you using (`go env`)?

<details><summary><code>go env</code> Output</summary><br><pre>
$ go env
// ...
GOARCH="amd64"
GOHOSTARCH="amd64"
GOHOSTOS="linux"
// ...
</pre></details>

### What version/commit of `govim` are you using?
```
git describe --tags
v0.0.33-13-ga8b8ff2
```

### What is the output of `:messages` in Vim?
`Messages maintainer: Bram Moolenaar <Bram@vim.org>`

### Do the Vim channel, `govim` or `gopls` log files show anything interesting?
Not that I could see:
```
[Trace - 19:40:28.849 PM] Sending request 'textDocument/codeAction - (14)'.
Params: {"textDocument":{"uri":"file:///path/to/nested/module/file.go"},"range":{"start":{"line":0,"character":0},"end":{"line":0,"character":0}},"context":{"diagnostics":null}}


[Trace - 19:40:28.851 PM] Received response 'textDocument/codeAction - (14)' in 2ms.
Result: [{"title":"Organize Imports","kind":"source.organizeImports","edit":{"documentChanges":[{"textDocument":{"version":0,"uri":"file:///path/to/vendor/path/to/nested/module/file.go"},"edits":[{"range":{"start":{"line":26,"character":0},"end":{"line":28,"character":0}},"newText":""}]}]}}]
```
so it seems that the path coming from gopls is different and is inside the vendor directory.

### How did you install `govim`?
`git clone`

### What did you do?

I have a nested submodule in my project and since this has been introduced, the experience with govim (or rather with gopls that comes with govim) was extremely frustrating. 
Every `gofmt` leads to an error:
```
E605: Exception not caught: got error whilst handling autocommand:2: got edits for file file:///path/to/vendor/path/to/nested/module/file.go but buffer is file:///path/to/pkg/nested/module/file.go
```
I have tried to manually turn on `ExperimentalWorkspaceModule` configuration option as it was reported to have helped with VSCode-based setups but it did not seem to have an effect. I'm not sure whether I enabled it in the correct place as I have not enough time to look into that.
Hence my question is whether it is possible to configure gopls in govim?

### What did you expect to see?
`gofmt` from vim works.

**Comment by myitcv** [comment]
@a-palchikov I've just pushed up support for `ExperimentalWorkspaceModule` in https://github.com/govim/govim/pull/1052
