### ISSUE TITLE
slow start after setting up shared gopls

### ISSUE THREAD

**Issue by ohait** [govim/govim#1060]
### What version of Vim/Gvim are you using?

<details><summary>Vim/Gvim version</summary><br><pre>
VIM - Vi IMproved 8.2 (2019 Dec 12, compiled Apr 22 2020 09:23:12)
Included patches: 1-616

</pre></details>

<pre>
$ go version
go version go1.15.8 linux/amd64
</pre>

### What operating system and processor architecture are you using (`go env`)?

<details><summary><code>go env</code> Output</summary><br><pre>
amd/64/linux/ubuntu
</pre></details>

### What version/commit of `govim` are you using?
govim is pulled from github, haven't updated for a while, last commit is from Sat Feb 13 05:44:20 2021 +0000

### What did you do?

enabled sharing gopls by setting 
<pre>
let $GOVIM_GOPLS_FLAGS="-remote=auto; -remote.listen.timeout=12h"
</pre>

### What did you expect to see?
when i close all the instances of vim, i have 2 daemons running, one for root and one for me:
<pre>
oha       7231  4.4 14.5 3741296 2356132 ?     Ssl  10:01   7:00 /home/oha/.vim/plugged/govim/cmd/govim/.bin/79ce8a0778bb18585d0c876a771334d35aa9ca10/gopls serve -listen unix;/run/user/1000/gopls-f094c3-daemon.oha -listen.timeout 12h0m0s
root      7530  0.1  0.1 1318004 30644 ?       Ssl  10:02   0:16 /home/oha/.vim/plugged/govim/cmd/govim/.bin/79ce8a0778bb18585d0c876a771334d35aa9ca10/gopls serve -listen unix;/tmp/gopls-f094c3-daemon.root -listen.timeout 12h0m0s
oha      17368  0.0  0.0  15984  1016 pts/3    S+   12:38   0:00 grep --color=auto gopls
</pre>

when i edit a .go file, it takes ~10s to read thru the packages, and ps shows those new processes:
<pre>
oha      17389 35.5  0.1 1455036 19692 ?       Ssl  12:38   0:00 /home/oha/.vim/plugged/govim/cmd/govim/.bin/79ce8a0778bb18585d0c876a771334d35aa9ca10/govim /home/oha/.vim/plugged/govim/cmd/govim/.bin/79ce8a0778bb18585d0c876a771334d35aa9ca10/gopls
oha      17408  1.5  0.1 1251388 19524 ?       Sl   12:38   0:00 /home/oha/.vim/plugged/govim/cmd/govim/.bin/79ce8a0778bb18585d0c876a771334d35aa9ca10/gopls -rpc.trace -logfile /tmp/gopls_20210319_1238_47_428751302.log -remote=auto; -remote.listen.timeout=12h
</pre>

which i think is correct, govim instance with gopls as an argument, and gopls itself which connects to the shared one.

### What did you see instead?

all looks good, but the expectation was a much faster cold start

starting a new instance of vim WHILE the old one is there has the same effect, ~10s start time

**Comment by myitcv** [comment]
> starting a new instance of vim WHILE the old one is there has the same effect, ~10s start time

I'll echo that this sound suspicious. What system are you running on here (that appears to be missing from your `go env` output)?

FYI - somewhat more definitive load times can be achieved by doing:

```
export GOVIM_LOGFILE_TMPL=%v
```

With that environment variable set, Vim will create the deterministically named log files:

```
$TMP/govim.log
$TMP/gopls.log
$TMP/vim_channel.log
```

That way you can then do the following:

```
tail -f /tmp/govim.log  | grep -i 'loading packages'
```

to clearly see the timings. 

@findleyr - I wonder if you could offer any suggestions on how best to debug this? Any help much appreciated.

**Comment by ohait** [comment]
```
2021-03-22T07:33:28.547917_#1:         "message": "Loading packages...",
2021-03-22T07:33:28.559079_#1: sendJSONMsg: [0,[58,"call","popup_create",["Loading packages...",""],{"border":[],"callback":"GOVIM_internal_ProgressClosed","close":"click","col":132,"firstline":1,"line":1,"mapping":0,"maxheight":10,"maxwidth":40,"minwidth":40,"padding":[0,1,0,1],"pos":"topright","scrollbar":false,"title":"Setting up workspace","wrap":false,"zindex":300}]]
2021-03-22T07:33:35.689306_#1:         "message": "Finished loading packages.",
2021-03-22T07:33:35.689870_#1: sendJSONMsg: [0,[60,"call","s:batchCall",[["call",["s:mustNoError",null],"popup_settext",1001,["Loading packages...","Finished loading packages.",""]],["call",["s:mustNoError",null],"popup_setoptions",1001,{"firstline":1,"time":3000}]]]]
```

**Comment by ohait** [comment]
after rebuilding a new version of vim it seems to be working now, possibly something was off on my local machine
