### ISSUE TITLE
cmd/govim: support gopls directoryFilters setting

### ISSUE THREAD

**Issue by elemir** [govim/govim#1073]
Hi!

I use govim with big monorepo but gopls have problem with monorepo support. Gopls developers recommend to add nonneeded directory to directoryFilters. But govim doesn't support it.

https://github.com/golang/tools/blob/master/gopls/doc/settings.md#directoryfilters-string

**Comment by myitcv** [comment]
@bbrodriges is working on this in https://github.com/govim/govim/pull/1020.

@bbrodriges is your PR still live? Would you like someone else to pick things up?
