### ISSUE TITLE
GOVIM on windows do not start

### ISSUE THREAD

**Issue by fiurthorn** [govim/govim#1118]
### What version of Vim/Gvim are you using?

<details><summary>Vim/Gvim version</summary><br><pre>
$ vim --version
VIM - Vi IMproved 8.2 (2019 Dec 12 kompiliert am May  2 2021 18:02:30)
MS-Windows 32 Bit Konsolen-Version
Inklusive der Patches: 1-2824
</pre></details>

### What version of Go are you using (`go version`)?

<pre>
$ go version
go version go1.17.1 windows/amd64
</pre>

### What operating system and processor architecture are you using (`go env`)?

<details><summary><code>go env</code> Output</summary><br><pre>
$ go env
set GOHOSTARCH=amd64
set GOHOSTOS=windows
</pre></details>

### What version/commit of `govim` are you using?

```
94367c3
```

### What is the output of `:messages` in Vim?

```
Fehler beim Ausführen von "C:\Users\s.weinmann\vimfiles\pack\plugins\start\govim\plugin\govim.vim[442]..function <SNR>21_install[11]..C:\Users\s.weinmann\vimfiles\pack\plugins\start\govim\plugin\govim.vim[442]..function <SNR>21_install":
Zeile   11:
E605: Exception nicht gefangen:
Fehler beim Ausführen von "C:\Users\s.weinmann\vimfiles\pack\plugins\start\govim\plugin\govim.vim":
Zeile  442:
E171: Fehlendes :endif
```

### How did you install `govim`?

Vim 8 packages

### What did you do?

Starting vim with activated GOVIM Plugin

### What did you expect to see?

No error ;-)

### What did you see instead?

```
lese "C:\Users\s.weinmann\vimfiles\pack\plugins\start\govim\plugin\govim.vim"
chdir(C:\Users\s.weinmann\vimfiles\pack\plugins\start\govim)
[global] C:\Users\s.weinmann\vimfiles\pack\plugins\start\govim
Rufe Shell auf, um "env -i git rev-parse HEAD 2>&1 > C:\Users\S7A71~1.WEI\AppData\Local\Temp\VF3773E.tmp" auszuf□hren
Fehler beim Ausf□hren von "C:\Users\s.weinmann\vimfiles\pack\plugins\start\govim\plugin\govim.vim[442]..function <SNR>21_install[11]..C:\Users\s.weinmann\vimfiles\pack\plugins\start\govim\plugin\govim.vim[442]..function <SNR>21_install":
Zeile   11:
E605: Exception nicht gefangen:
Fehler beim Ausf□hren von "C:\Users\s.weinmann\vimfiles\pack\plugins\start\govim\plugin\govim.vim":
Zeile  442:
E171: Fehlendes :endif
Lesen von C:\Users\s.weinmann\vimfiles\pack\plugins\start\govim\plugin\govim.vim beendet
lese "C:\Users\s.weinmann\vimfiles\pack\plugins\start\govim\ftdetect\go.vim"
```

**Comment by fiurthorn** [comment]
found 

```
  " Note that we use "env -i" to use git with an empty environment.
  " Otherwise, using vim with govim as the editor in "git commit" will break,
  " as "git commit" will set GIT_DIR, which "git rev-parse" will follow.
  " We'd then end up with the user's in-progress commit, not govim's HEAD.
  " TODO: make work on Windows
```

**Comment by fiurthorn** [comment]
this may fix it on windows:

```
  let git = trim(system("which git"))
  let commit = trim(system("env -i ".git." rev-parse HEAD 2>&1"))
```

**Comment by fiurthorn** [comment]
not interested in closing bugs?

**Comment by leitzler** [comment]
Hi @fiurthorn, sorry for the delay. Windows is unfortunately not very tested, there are for example no CI tests for Windows.

From my point of view that is mainly because I don't have access to any Windows environment to test things on.
Looking at the diff you added (thanks!) I can't really understand why it would make a difference to run `which git`, could you provide any more details?

**Comment by fiurthorn** [comment]
It looks for me that `env -i` strips all environment variables including `$PATH`, so the SHELL could not find git.

**Comment by leitzler** [comment]
interesting, I had no idea Windows differed from Linux and macOS. Running `env -i echo $PATH` does indeed print the path for me (as set by `.profile` / `.zshrc`).

I can't see how your patch would cause any problems, thanks for looking into this! Please submit a pull request.

**Comment by fiurthorn** [comment]
```bat
$>env -i git
env: 'git': No such file or directory

$>where git
C:\Program Files\Git\cmd\git.exe

$>env -i "C:\Program Files\Git\cmd\git.exe"
usage: git [--version] [--help] [-C <path>] [-c <name>=<value>]
```
