### ISSUE TITLE
cmd/govim: test failure in go_to_def_newtab

### ISSUE THREAD

**Issue by myitcv** [govim/govim#344]
```
ok  	github.com/myitcv/govim	8.524s
--- FAIL: TestScripts (14.11s)
    --- FAIL: TestScripts/scripts (0.00s)
        --- FAIL: TestScripts/scripts/go_to_def_newtab (1.23s)
            testscript.go:308: 
                # Test that GOVIMGoToDef works
                # More natural to split below and to the right (0.039s)
                # Definition in unopened buffer; newtab (0.149s)
                > vim ex 'set switchbuf=newtab'
                > vim ex 'e '$WORK/p.go
                > vim ex 'call cursor(5,17)'
                > vim ex 'GOVIMGoToDef'
                [stderr]
                unexpected command error: failed to ex(GOVIMGoToDef) in Vim: Caught 'got error whilst handling command:GOVIMGoToDef: should have resolved a buffer; we didn''t' in function <SNR>18_userBusy[3]..GOVIM_internal_SetUserBusy[2]..<SNR>18_callbackFunction[2]..<SNR>18_define[40]..<SNR>18_callbackCommand, line 5
                [exit status 255]
                FAIL: testdata/go_to_def_newtab.txt:11: unexpected command failure
```

I suspect this can happen in very rare situations where the `CursorHold,CursorHoldI` timeout happens during/immediately after we open the file containing the definition in a new tab (in this case), i.e. before Vim has fired the `EventBufRead,EventBufNewFile` event `govim` has registered. 

Suspect we can ignore as a flake... but opening in case of further instances.

Marking as a Vim issue, because if the hypothesis above is correct then the `CursorHold,CursorHoldI` should be fired after the `EventBufRead,EventBufNewFile` event.

**Comment by leitzler** [comment]
Here is an example of how the log looks like when it occurs: https://gist.github.com/leitzler/0f7a6f67f073740c660fde0be11110dd

**Comment by myitcv** [comment]
We haven't seen this in a while so closing.
