### ISSUE TITLE
cmd/govim: properly handle LSP client ShowMessage

### ISSUE THREAD

**Issue by myitcv** [govim/govim#445]
In https://github.com/myitcv/govim/pull/467 we simply log the fact that the server asked us (the client) to show a message. If the message is important we should show it, preferably as a popup.

**Comment by dragfire** [comment]
Hi @myitcv, I would like to work on this. It would be very helpful if you could push me in the right direction. How do you decide if a message is important or not?

**Comment by myitcv** [comment]
Thanks for the interest @dragfire 

> It would be very helpful if you could push me in the right direction

Very happy to. First thing to say: I think it's probably worth waiting for https://github.com/myitcv/govim/pull/467 to be merged before tackling this. Because it's the upgrade of `gopls` that causes these calls to be made.

> How do you decide if a message is important or not?

But you can, by all means, have a poke around. Taking a look at the client method:

https://github.com/myitcv/govim/blob/956c1ebcc75bed45653d44f26109d9bca1a772ad/cmd/govim/gopls_client.go#L21-L23

the second parameter has a type defined as follows:

https://github.com/golang/tools/blob/master/internal/lsp/protocol/tsprotocol.go#L1731-L1742

The `Type` field is in effect an enumeration:

https://github.com/golang/tools/blob/master/internal/lsp/protocol/tsprotocol.go#L3579-L3597

So in the first instance I think we want to show a notification popup when we receive a message of `Error` type.

What do I mean by a notification popup? I've proposed a potential approach in https://github.com/myitcv/govim/issues/318#issuecomment-513582991. That results in something like the following:

![Screen Shot 2019-09-04 at 16 06 37](https://user-images.githubusercontent.com/3374574/64267310-163c3300-cf2e-11e9-8da0-7b79c7978986.png)

See `:help popup_create-arguments` for more popup options.

Please feel free to ask any questions you like. Having new contributors helps to ensure that our docs (or lack thereof right now) for (new) contributors are up-to-date, sufficient etc.

**Comment by dragfire** [comment]
@myitcv Thank you so much. I will play around with this a bit. Looking forward to contributing to this repo.

**Comment by myitcv** [comment]
We just merged https://github.com/myitcv/govim/pull/487, so please feel free to have a play around against 6961210ff30a5862594ff04dde9f3a5f62120ae4

**Comment by dragfire** [comment]
@myitcv I just implemented a `popup_create` channel call for `Error` `MeesageType`. But I am not sure how to test this method. Please have a look at: [https://github.com/dragfire/govim/blob/master/cmd/govim/gopls_client.go#L21-L34](https://github.com/dragfire/govim/blob/master/cmd/govim/gopls_client.go#L21-L34) 

How do I test that this particular method is working? And if I want to see the popup being displayed on my local machine, how to do that?

**Comment by myitcv** [comment]
@dragfire 

> But I am not sure how to test this method

Great question. 

We could wait for https://go-review.googlesource.com/c/tools/+/194018 to land in `gopls`, then create a test that triggers this error. 

Whilst we wait for point 1, we could in the meantime simulate a message from `gopls`. The way to do this would be to create a test-only Vim function, similar to `GOVIM_internal_DumpPopups`:

https://github.com/govim/govim/blob/74faeda6b8893a4bf040becc4218426da282c7c5/cmd/govim/test_config.go#L36

This function would need to asynchronously trigger a call to:

https://github.com/govim/govim/blob/74faeda6b8893a4bf040becc4218426da282c7c5/cmd/govim/gopls_client.go#L21

We can then call that Vim function from a test, for example see:

https://github.com/govim/govim/blob/74faeda6b8893a4bf040becc4218426da282c7c5/cmd/govim/testdata/hover.txt#L13

Please feel free to start a PR. It's often easier to add comments to code.
