### ISSUE TITLE
test: add option to save testscript work dir

### ISSUE THREAD

**Issue by leitzler** [govim/govim#456]
# What version/commit of `govim` are you using?
Latest `master`, dea863fefc545e66b7f3a57e0485a81395e6bdbc

### What did you do?
Run the test suite.

### What did you expect to see?
Logfiles are written to `/tmp/go-test-scriptNNNNNNNNNN/` by the testscript framework that is forked by @rogpeppe to https://github.com/rogpeppe/go-internal/blob/master/testscript/testscript.go

The origin (and the fork) has a flag named `-testwork`, and in the origin that can be used to keep the work dir:
 https://github.com/golang/go/blob/25a2b98f7a1454aac0d7d3072f74613ac0446630/src/cmd/go/script_test.go#L53-L55

In the fork the persistence decision has been moved to testscript parameters:
https://github.com/rogpeppe/go-internal/blob/master/testscript/testscript.go#L169-L177

When govim run the tests it nevers sets this parameter to `true`. 

### What did you see instead?
Work dir always removed, even when starting with `-testwork`.

**Comment by leitzler** [comment]
I don't know the reason behind moving the persistence decision, maybe this should be fixed in https://github.com/rogpeppe/go-internal?

Otherwise we could add an env var, `GOVIM_TESTSCRIPT_KEEPWORKDIR` so it is possible to keep them.

**Comment by leitzler** [comment]
Forgot to talk to Roger about this in London, raised https://github.com/rogpeppe/go-internal/issues/78

**Comment by rogpeppe** [comment]
This is definitely a bug. The flag is actually  defined, but is not used properly. Looks like I made a half-arsed job of translating that bit. Given that we export the parameter currently, I'd suggest that we keep the directory around if either the flag or the parameter are set.

**Comment by myitcv** [comment]
Sounds good @rogpeppe. @leitzler did you want to raise a PR over at `go-internal`?

**Comment by leitzler** [comment]
Oh, forgot about this. Raised https://github.com/rogpeppe/go-internal/pull/80
