### ISSUE TITLE
cmd/govim: support completions from unimported packages

### ISSUE THREAD

**Issue by myitcv** [govim/govim#463]
Now that https://go-review.googlesource.com/c/tools/+/190338 has landed, we will need to enhance our completion support to fully handle the response to [`textDocument/completion`](https://github.com/Microsoft/language-server-protocol/blob/gh-pages/specification.md#completion-request-leftwards_arrow_with_hook) which can (and will in this case) have additional text edits.

**Comment by cespare** [comment]
Nice!

**Comment by myitcv** [comment]
Unfortunately we're currently blocked on https://github.com/golang/go/issues/33647

**Comment by myitcv** [comment]
Actually marking that this is blocked on #487

**Comment by myitcv** [comment]
This is no longer blocked so if someone wants to give this a crack, please do.

**Comment by myitcv** [comment]
This already landed. See https://github.com/govim/govim/wiki/govim-plugin-API#%EF%B8%8F-code-completion for details
