### ISSUE TITLE
cmd/govim: bump minimum required Vim version to v8.1.1711

### ISSUE THREAD

**Issue by myitcv** [govim/govim#484]
v8.1.1657 is the baseline Vim version we require in order for popups windows to be enabled:

https://github.com/myitcv/govim/blob/0d81777c4c13b188013f825cb6fe259f77d4a11a/testsetup/testsetup.go#L37-L39

v8.1.1657 was "released" on 9 Jul 2019: https://github.com/vim/vim/releases/tag/v8.1.1657

v8.1.1711 is the baseline Vim version we require in order to use incremental sync:

https://github.com/myitcv/govim/blob/0d81777c4c13b188013f825cb6fe259f77d4a11a/testsetup/testsetup.go#L33-L35

v8.1.1711 was "released" on 17 Jul 2019: https://github.com/vim/vim/releases/tag/v8.1.1711

I'd like to propose:

* adding the latest Vim version to matrix to keep up (v8.1.1983  at the time of writing): https://github.com/myitcv/govim/blob/956c1ebcc75bed45653d44f26109d9bca1a772ad/testsetup/testsetup.go#L48
* updating the baseline Vim version required for `govim` to v8.1.1711
* dropping the option for disabling incremental updates: https://github.com/myitcv/govim/blob/master/testsetup/testsetup.go#L25
* dropping the option for disabling popup windows: https://github.com/myitcv/govim/blob/master/testsetup/testsetup.go#L26

Please reply with comments on this proposal if you foresee issues with this plan.

cc @leitzler @mvdan @milesbxf

**Comment by mvdan** [comment]
Sounds good to me. The only disadvantage I can see is people on stable/older systems, like Ubuntu LTS. But those people would already have other issues, like older Go versions. I think govim will require a recent setup for as long as it's moving fast, and I think that's fine.

**Comment by myitcv** [comment]
@mvdan thanks for your thoughts.

> The only disadvantage I can see is people on stable/older systems, like Ubuntu LTS.

Indeed. I'm unclear even whether they meet the current bar of v8.1.1158. 

> I think govim will require a recent setup for as long as it's moving fast, and I think that's fine.

Agreed.

**Comment by cespare** [comment]
I'm on Ubuntu 18.04 and I already have to build vim from source to use govim.

**Comment by leitzler** [comment]
SGTM, agree with Daniel

**Comment by myitcv** [comment]
Thanks for the quick responses. Feels like this is not a terrible idea, so let's go ahead.

**Comment by leitzler** [comment]
Closed as #501 was merged
