### ISSUE TITLE
cmd/govim: re-use a single gopls instance (over sockets)

### ISSUE THREAD

**Issue by myitcv** [govim/govim#491]
For the ultimate in speed/efficiency, we should share a single `gopls` instance between `govim` instances. This means switching to communicating over sockets.

This becomes particularly important when it comes to things like pre-warming the imports cache:

https://github.com/golang/go/issues/32750#issuecomment-528314462

Questions:

* what to do with logging; we will still have the same number of `govim` instances, so they can continue to log as before. But we will need to communicate the logfile location of `gopls` back to the editor

Pre-requisites:

* might need to properly implement workspace folders https://github.com/myitcv/govim/issues/172
* (less likely) might require some level of configuration preference per editor instance (at the moment there is only a top-level `gopls` configuration, and then workspace specific values)

Notes:

* we'd still want to run test scripts with their own "isolated" instance of `gopls` 
* unclear we'd need to keep the `stdin/stdout` communication option - instead just control whether a `govim` instance should look for the daemon or start it's own version
* we'd want to add tests to ensure the many-to-one operation works

**Comment by myitcv** [comment]
On holding pending answer on using `gopls` over sockets in https://github.com/golang/go/issues/32750#issuecomment-528314462

**Comment by jeremydonahue** [comment]
Hi! Now that golang/go#34111 is closed, I was wondering if there's anything I can do to help move this issue forward?

**Comment by myitcv** [comment]
Thanks for the prod, @jeremydonahue. Great news is that full support has landed in `gopls`, and as of v0.0.30 of `govim` you can use the multi-client feature.

I've just updated the [release notes for v0.0.30](https://github.com/govim/govim/releases/tag/v0.0.30) to link to the relevant docs:

https://github.com/golang/tools/blob/63da46f3035e/gopls/doc/daemon.md

I'll close this issue given everything is implemented as expected. Please raise new issues or chat over in `#govim` on Slack with any questions.
