### ISSUE TITLE
cmd/govim: add/enable support for suggested fixes

### ISSUE THREAD

**Issue by myitcv** [govim/govim#510]
Suggested fixes, from `go/analysis` analysers, when enabled, will be returned in response to the `CodeAction` call. 

This issue tracks enabling and adding support for such code action responses. 

Things to do/consider:

* work out UI/UX around presenting suggested fixes and then applying them. Could use another mode for the quickfix window (current used for diagnostics or references), with a key mapping, perhaps `A`, to apply the edit (`Enter` would jump to the location of the fix)
* disambiguate within the existing format code which code action to apply (because the `source.organizeImprots` kind will be one of many returned)

**Comment by myitcv** [comment]
@leitzler I think we're done here, at least for initial support, so good to close?

**Comment by leitzler** [comment]
Indeed!
