### ISSUE TITLE
govim code completion not showing suggestions

### ISSUE THREAD

**Issue by ehrktia** [govim/govim#549]
### What version of Vim/Gvim are you using?
VIM - Vi IMproved 8.1 (2018 May 18, compiled Sep  8 2019 07:17:45)
macOS version
Included patches: 1-1999
Compiled by Homebrew

<details><summary>Vim/Gvim version</summary><br><pre>
$ vim --version
Huge version without GUI.  Features included (+) or not (-):
+acl               -farsi             -mouse_sysmouse    -tag_any_white
+arabic            +file_in_path      +mouse_urxvt       -tcl
+autocmd           +find_in_path      +mouse_xterm       +termguicolors
+autochdir         +float             +multi_byte        +terminal
-autoservername    +folding           +multi_lang        +terminfo
-balloon_eval      -footer            -mzscheme          +termresponse
+balloon_eval_term +fork()            +netbeans_intg     +textobjects
-browse            +gettext           +num64             +textprop
++builtin_terms    -hangul_input      +packages          +timers
+byte_offset       +iconv             +path_extra        +title
+channel           +insert_expand     +perl              -toolbar
+cindent           +job               +persistent_undo   +user_commands
-clientserver      +jumplist          +postscript        +vartabs
+clipboard         +keymap            +printer           +vertsplit
+cmdline_compl     +lambda            +profile           +virtualedit
+cmdline_hist      +langmap           -python            +visual
+cmdline_info      +libcall           +python3           +visualextra
+comments          +linebreak         +quickfix          +viminfo
+conceal           +lispindent        +reltime           +vreplace
+cryptv            +listcmds          +rightleft         +wildignore
+cscope            +localmap          +ruby              +wildmenu
+cursorbind        +lua               +scrollbind        +windows
+cursorshape       +menu              +signs             +writebackup
+dialog_con        +mksession         +smartindent       -X11
+diff              +modify_fname      -sound             -xfontset
+digraphs          +mouse             +spell             -xim
-dnd               -mouseshape        +startuptime       -xpm
-ebcdic            +mouse_dec         +statusline        -xsmp
+emacs_tags        -mouse_gpm         -sun_workshop      -xterm_clipboard
+eval              -mouse_jsbterm     +syntax            -xterm_save
+ex_extra          +mouse_netterm     +tag_binary
+extra_search      +mouse_sgr         -tag_old_static
   system vimrc file: "$VIM/vimrc"
     user vimrc file: "$HOME/.vimrc"
 2nd user vimrc file: "~/.vim/vimrc"
      user exrc file: "$HOME/.exrc"
       defaults file: "$VIMRUNTIME/defaults.vim"
  fall-back for $VIM: "/usr/local/share/vim"
Compilation: clang -c -I. -Iproto -DHAVE_CONFIG_H   -DMACOS_X -DMACOS_X_DARWIN  -g -O2 -U_FORTIFY_SOURCE -D_FORTIFY_SOURCE=1
Linking: clang   -L. -fstack-protector-strong -L/usr/local/lib -L/usr/local/opt/libyaml/lib -L/usr/local/opt/openssl@1.1/lib -L/usr/local/opt/readline/lib  -L/usr/local/lib -o vim        -lncurses -liconv -lintl -framework AppKit  -L/usr/local/opt/lua/lib -llua5.3 -mmacosx-version-min=10.14 -fstack-protector-strong -L/usr/local/lib  -L/usr/local/Cellar/perl/5.30.0/lib/perl5/5.30.0/darwin-thread-multi-2level/CORE -lperl -lm -lutil -lc  -L/usr/local/opt/python/Frameworks/Python.framework/Versions/3.7/lib/python3.7/config-3.7m-darwin -lpython3.7m -framework CoreFoundation  -lruby.2.6

</pre></details>

### What version of Go are you using (`go version`)?
go version go1.13 darwin/amd64
<pre>
$ go version
go version go1.13 darwin/amd64

</pre>

### What operating system and processor architecture are you using (`go env`)?
GO111MODULE=""
GOARCH="amd64"
GOBIN=""
GOCACHE="/Users/karthickayyapillai/Library/Caches/go-build"
GOENV="/Users/karthickayyapillai/Library/Application Support/go/env"
GOEXE=""
GOFLAGS=""
GOHOSTARCH="amd64"
GOHOSTOS="darwin"
GONOPROXY=""
GONOSUMDB=""
GOOS="darwin"
GOPATH="/Users/karthickayyapillai/go"
GOPRIVATE=""
GOPROXY="https://proxy.golang.org,direct"
GOROOT="/usr/local/Cellar/go/1.13/libexec"
GOSUMDB="sum.golang.org"
GOTMPDIR=""
GOTOOLDIR="/usr/local/Cellar/go/1.13/libexec/pkg/tool/darwin_amd64"
GCCGO="gccgo"
AR="ar"
CC="clang"
CXX="clang++"
CGO_ENABLED="1"
GOMOD="/Users/karthickayyapillai/.vim/bundle/govim/go.mod"
CGO_CFLAGS="-g -O2"
CGO_CPPFLAGS=""
CGO_CXXFLAGS="-g -O2"
CGO_FFLAGS="-g -O2"
CGO_LDFLAGS="-g -O2"
PKG_CONFIG="pkg-config"
GOGCCFLAGS="-fPIC -m64 -pthread -fno-caret-diagnostics -Qunused-arguments -fmessage-length=0 -fdebug-prefix-map=/var/folders/wk/2mxs2gf122x1knb02422fwcw0000gn/T/go-build718721993=/tmp/go-build -gno-record-gcc-switches -fno-common"
<details><summary><code>go env</code> Output</summary><br><pre>
$ go env

</pre></details>

### What version/commit of `govim` are you using?
v0.0.24

### What is the output of `:messages` in Vim?
---Omni completion (^O ^N ^P) Pattern not found

### Do the Vim channel, `govim` or `gopls` log files show anything interesting?

/var/folders/wk/2mxs2gf122x1knb02422fwcw0000gn/T//vim_channel_log_20190926_2228_14_BohWgnZfnHaq

### How did you install `govim`?
git clone 

pathogen package manager
### What did you do?
create a simple go file 
typed fmt.Prin and then pressed <C-O><C-X> as per the tip provided.

```
package main
func main(){
fmt.Println()}
```
### What did you expect to see?
provide list of available options associated with fmt package.

### What did you see instead?
---Omni completion (^O ^N ^P) Pattern not found

### vimrc

````

let g:go_def_mode='gopls'
let g:go_info_mode='gopls'
set ttymouse=sgr
" Suggestion: To make govim/Vim more responsive/IDE-like, we suggest a short
" balloondelay
set balloondelay=150
set updatetime=500
set signcolumn=number
set signcolumn=yes
set bs=2
set tw=80
set colorcolumn=80
````

basic options for provided vimrc in readme.

**Comment by myitcv** [comment]
@ehrktia apologies, this appears to have slipped through the next.

In the example above you are missing the `fmt` import. Hence this code will not complete.

We are tracking adding support for unimported packages in https://github.com/govim/govim/issues/463 but that has not landed yet, so you will need to add the `fmt` import for now.

Does that help to answer things?

**Comment by ehrktia** [comment]
Thanks for your help ,let me try the suggestion
