### ISSUE TITLE
cmd/govim: add support for highlighting references

### ISSUE THREAD

**Issue by myitcv** [govim/govim#559]
We should use [text properties](https://vimhelp.org/textprop.txt.html) to do this properly/quickly.

Questions:

* should we add a separate command to remove the highlighting? Probably yes
* if we make a change and the references highlighting is active, should we re-calculate references and re-highlight? Probably yes

**Comment by myitcv** [comment]
Apparently should be using https://microsoft.github.io/language-server-protocol/specifications/specification-3-15/#textDocument_documentHighlight for this.

Would only want to do this after `updatetime`, per the logic for updating quickfix etc.

**Comment by leitzler** [comment]
[![asciicast](https://asciinema.org/a/ipqSU5qUZDnxYEkXVfATqUcj2.svg)](https://asciinema.org/a/ipqSU5qUZDnxYEkXVfATqUcj2)

Any ideas for how the default highlight group should look like? The recording above is when using `cterm=reverse`.

**Comment by myitcv** [comment]
I'd say that looks like a great starting point!
