### ISSUE TITLE
cmd/govim: index out of range panic from gopls

### ISSUE THREAD

**Issue by stmuk** [govim/govim#586]
I'm tracking vim from git daily and update govim frequently on both macOS and Linux but have often  noticed issues with gopls (freezing vim and long error messages), although I'm also using vim-go at the same time. 

Before I dive deeper into working out what's going wrong I'm wondering I I should I be using a tagged version of gopls or just update gopls frequently?

**Comment by myitcv** [comment]
Hi @stmuk - you are, unfortunately, running into an issue with the latest version of `govim`. However that issue is in fact a `gopls` issue. With `gitaly` (using commit b1250c2b9dda443aa5eb146776b4a55df6114456), 5deab50f6089cce13b839395655cb7025f305789 of `govim`, and `v8.1.2292` of Vim, I see the following panic in the `govim` logs:

```
panic: runtime error: index out of range [0] with length 0

goroutine 52 [running]:
golang.org/x/tools/internal/lsp/cache.(*session).bestView(0xc000157340, 0xc00048e330, 0x29, 0x0, 0x0)
	/home/myitcv/gostuff/pkg/mod/golang.org/x/tools@v0.0.0-20191112184959-323f198cedfe/internal/lsp/cache/session.go:227 +0x19b
golang.org/x/tools/internal/lsp/cache.(*session).DidOpen(0xc000157340, 0xd722a0, 0xc000336c90, 0xc00048e330, 0x29, 0x0, 0xc000430300, 0x1, 0x8, 0xaf2680, ...)
	/home/myitcv/gostuff/pkg/mod/golang.org/x/tools@v0.0.0-20191112184959-323f198cedfe/internal/lsp/cache/session.go:295 +0x2b8
golang.org/x/tools/internal/lsp.(*Server).didOpen(0xc0001f3aa0, 0xd722a0, 0xc000336c90, 0xc000498180, 0x0, 0xc0005960b0)
	/home/myitcv/gostuff/pkg/mod/golang.org/x/tools@v0.0.0-20191112184959-323f198cedfe/internal/lsp/text_synchronization.go:29 +0x15e
golang.org/x/tools/internal/lsp.(*Server).DidOpen(0xc0001f3aa0, 0xd722a0, 0xc000336c90, 0xc000498180, 0xc000498180, 0x0)
	/home/myitcv/gostuff/pkg/mod/golang.org/x/tools@v0.0.0-20191112184959-323f198cedfe/internal/lsp/server.go:135 +0x49
golang.org/x/tools/internal/lsp/protocol.serverHandler.Deliver(0xd878c0, 0xc0001f3aa0, 0xd722a0, 0xc000336c90, 0xc000310a40, 0xc000336c00, 0xc00031c140)
	/home/myitcv/gostuff/pkg/mod/golang.org/x/tools@v0.0.0-20191112184959-323f198cedfe/internal/lsp/protocol/tsserver.go:111 +0x1e32
golang.org/x/tools/internal/jsonrpc2.(*Conn).Run.func1(0xc00010e6c0, 0xc000310a40, 0xc0001f3b00, 0xd722a0, 0xc000336c90, 0x0, 0x0, 0xc000304830)
	/home/myitcv/gostuff/pkg/mod/golang.org/x/tools@v0.0.0-20191112184959-323f198cedfe/internal/jsonrpc2/jsonrpc2.go:370 +0x160
created by golang.org/x/tools/internal/jsonrpc2.(*Conn).Run
	/home/myitcv/gostuff/pkg/mod/golang.org/x/tools@v0.0.0-20191112184959-323f198cedfe/internal/jsonrpc2/jsonrpc2.go:354 +0x874
```

https://github.com/govim/govim/pull/588 will fix the problem you are seeing. Should be merged later today.

The reason this didn't get caught when we released `v0.0.25` is somewhat interesting/frustrating. One of our integration tests has been marked as `skip` for some time:

https://github.com/govim/govim/blob/5deab50f6089cce13b839395655cb7025f305789/cmd/govim/testdata/scenario_default/format_on_save_new_file.txt#L3

whilst we await a fix for https://github.com/golang/go/issues/35114 and friends. 

However this test being marked as `skip` also meant that another bug managed to sneak through.

**Comment by stmuk** [comment]
@myitcv Thanks for this. I'll try updating shortly. 

I did notice another oddity which is that govim seems to be starting *two* different versions of gopls  - an old version I had knocking around under $GOPATH/bin  as well as the correct one as specified in go.mod! Not sure if govim is actually using the older version but I'll going to delete it.

````
$ ps axl|grep [g]opls
0  1000  2417  2332  20   0 234852  7208 pipe_w Ssl  ?          0:00 /home/steve/.vim/pack/stmuk/start/govim/cmd/govim/.bin/59308f1b9d9c6d03c41ef2a0656a2524d6d1ae40/govim /home/steve/.vim/pack/stmuk/start/govim/cmd/govim/.bin/59308f1b9d9c6d03c41ef2a0656a2524d6d1ae40/gopls
0  1000  2421  2332  20   0 390768 154380 pipe_w Ssl ?          0:01 /home/steve/go/bin/gopls
0  1000  2449  2417  20   0 466964 154120 futex_ Sl  ?          0:01 /home/steve/.vim/pack/stmuk/start/govim/cmd/govim/.bin/59308f1b9d9c6d03c41ef2a0656a2524d6d1ae40/gopls -rpc.trace -logfile /tmp/gopls_log_20191118_1722_57_624547158
````

$ /home/steve/go/bin/gopls version
version v0.1.6-cmd.gopls, built in $GOPATH mode

**Comment by myitcv** [comment]
@stmuk - I forgot to mention that in my last response. Using `govim` and `vim-go` together is likely to cause problems. Each will start its own `gopls` instance for one. `govim` uses a version pinned through its `go.mod`; `vim-go` uses a version from your `PATH`.

They are, largely, trying to solve the same problem. Is there a reason you still need `vim-go`? There are, admittedly, a number of features we haven't yet implemented here in `govim` land. If there are specific ones you'd be interested in, please do make sure we have issues covering them at least. If you want to contribute even better :)

**Comment by myitcv** [comment]
@stmuk #588 is now merged, so please give 806674b9d799bebda41122ce143c234e961bbc97 a try.

**Comment by stmuk** [comment]
@myitcv This seems much more stable so far! Thanks.

**Comment by myitcv** [comment]
Great, thanks for reporting back @stmuk. I'll close this for now, but we can easily reopen/open a new issue if you see further problems.
