### ISSUE TITLE
cmd/govim: make quickfix gutter sign customizable

### ISSUE THREAD

**Issue by llimllib** [govim/govim#633]
As far as I can tell, the quickfix sign is locked to `>>` in govim: https://github.com/govim/govim/blob/master/cmd/govim/signs.go#L44. I would love to be able to customize this.

(If it is customizable, I apologize! I looked hard for docs that suggested it was and even took a shot at tracing the code a bit. Also I elided all of the bug reporting sections of this issue because I'm not reporting a bug)

**Comment by myitcv** [comment]
cc @leitzler

**Comment by leitzler** [comment]
You are right, it is indeed hard coded today.

The text used for signs is defined per sign type in vim, i.e. there is one for errors and another one for warnings. We probably don't want to add custom settings for each severity.

I'll take a look at this, maybe we can let govim check if the user already have the sign types defined before defining them so the users can override the entire sign type in their vimrc.

**Comment by leitzler** [comment]
@llimllib You can try out #643 and see if that works for you.
