### ISSUE TITLE
cmd/govim: document a command for wrapping to the next error in a buffer

### ISSUE THREAD

**Issue by llimllib** [govim/govim#642]
My first cut at a section for https://github.com/govim/govim/wiki/vimrc-tips, after a discussion with @myitcv and @findleyr on slack:

#### 💡 Tip: wrapping to the next error in the current buffer

Vim has a helpful command `:cbelow` which will go to the next error in the current buffer below the cursor location, but it will not wrap around to the top of the file. If you would like to have a shortcut which goes to the next error in the file and wraps around to the top, you can define a command and bind it to a keystroke with something like this in your `.vimrc`:

```vim
command! Cnext try | cbelow | catch | cabove 9999 | catch | endtry
nnoremap <leader>m :Cnext<CR>
```

#### end tip

This command appears to be novel, at least I can't find a reference to it, and I find it very useful.

I haven't broadened the scope of the tip to "ways to navigate quickfix", but can if that's desired

**Comment by myitcv** [comment]
@llimllib thank you very much for this. Apologies, I've got no idea how I missed the issue when you first raised it. 

> I haven't broadened the scope of the tip to "ways to navigate quickfix", but can if that's desired

I think that would be useful, but let's include the tip as-is for now:

https://github.com/govim/govim/wiki/vimrc-tips#-tip-wrapping-to-the-next-error-in-the-current-buffer

For example, I use (and encourage people to consider) https://github.com/tpope/vim-unimpaired. But for me `]q` (which is `:cnext`) doesn't really cut if for the same reason that you wrote this tip. I would actually prefer `]q` to be mapped to a slight variation of your proposal:

```
command! Cnext try | cbelow | catch | cnext | catch | endtry
```

Thanks again.
