### ISSUE TITLE
cmd/govim: underlining is too aggressive in staticcheck mode

### ISSUE THREAD

**Issue by llimllib** [govim/govim#644]
### What version of Vim/Gvim are you using?

<details><summary>Vim/Gvim version</summary><br><pre>
$ vim --version
VIM - Vi IMproved 8.2 (2019 Dec 12, compiled Dec 12 2019 16:52:17)
macOS version
Compiled by Homebrew
Huge version without GUI.  Features included (+) or not (-):
+acl               -farsi             -mouse_sysmouse    -tag_old_static
+arabic            +file_in_path      +mouse_urxvt       -tag_any_white
+autocmd           +find_in_path      +mouse_xterm       -tcl
+autochdir         +float             +multi_byte        +termguicolors
-autoservername    +folding           +multi_lang        +terminal
-balloon_eval      -footer            -mzscheme          +terminfo
+balloon_eval_term +fork()            +netbeans_intg     +termresponse
-browse            +gettext           +num64             +textobjects
++builtin_terms    -hangul_input      +packages          +textprop
+byte_offset       +iconv             +path_extra        +timers
+channel           +insert_expand     +perl              +title
+cindent           +job               +persistent_undo   -toolbar
-clientserver      +jumplist          +popupwin          +user_commands
+clipboard         +keymap            +postscript        +vartabs
+cmdline_compl     +lambda            +printer           +vertsplit
+cmdline_hist      +langmap           +profile           +virtualedit
+cmdline_info      +libcall           -python            +visual
+comments          +linebreak         +python3           +visualextra
+conceal           +lispindent        +quickfix          +viminfo
+cryptv            +listcmds          +reltime           +vreplace
+cscope            +localmap          +rightleft         +wildignore
+cursorbind        +lua               +ruby              +wildmenu
+cursorshape       +menu              +scrollbind        +windows
+dialog_con        +mksession         +signs             +writebackup
+diff              +modify_fname      +smartindent       -X11
+digraphs          +mouse             -sound             -xfontset
-dnd               -mouseshape        +spell             -xim
-ebcdic            +mouse_dec         +startuptime       -xpm
+emacs_tags        -mouse_gpm         +statusline        -xsmp
+eval              -mouse_jsbterm     -sun_workshop      -xterm_clipboard
+ex_extra          +mouse_netterm     +syntax            -xterm_save
+extra_search      +mouse_sgr         +tag_binary        
   system vimrc file: "$VIM/vimrc"
     user vimrc file: "$HOME/.vimrc"
 2nd user vimrc file: "~/.vim/vimrc"
      user exrc file: "$HOME/.exrc"
       defaults file: "$VIMRUNTIME/defaults.vim"
  fall-back for $VIM: "/usr/local/share/vim"
Compilation: clang -c -I. -Iproto -DHAVE_CONFIG_H   -DMACOS_X -DMACOS_X_DARWIN  -g -O2 -U_FORTIFY_SOURCE -D_FORTIFY_SOURCE=1       
Linking: clang   -L. -fstack-protector-strong -L/usr/local/lib -L/usr/local/opt/libyaml/lib -L/usr/local/opt/openssl@1.1/lib -L/usr/local/opt/readline/lib  -L/usr/local/lib -o vim        -lncurses -liconv -lintl -framework AppKit  -L/usr/local/opt/lua/lib -llua5.3 -mmacosx-version-min=10.15 -fstack-protector-strong -L/usr/local/lib  -L/usr/local/Cellar/perl/5.30.0/lib/perl5/5.30.0/darwin-thread-multi-2level/CORE -lperl -lm -lutil -lc  -L/usr/local/opt/python/Frameworks/Python.framework/Versions/3.7/lib/python3.7/config-3.7m-darwin -lpython3.7m -framework CoreFoundation  -lruby.2.6     

</pre></details>

### What version of Go are you using (`go version`)?

<pre>
$ go version
go version go1.13 darwin/amd64

</pre>

### What operating system and processor architecture are you using (`go env`)?

<details><summary><code>go env</code> Output</summary><br><pre>
$ go env
GO111MODULE=""
GOARCH="amd64"
GOBIN="/Users/llimllib/go/bin"
GOCACHE="/Users/llimllib/Library/Caches/go-build"
GOENV="/Users/llimllib/Library/Application Support/go/env"
GOEXE=""
GOFLAGS=""
GOHOSTARCH="amd64"
GOHOSTOS="darwin"
GONOPROXY=""
GONOSUMDB=""
GOOS="darwin"
GOPATH="/Users/llimllib/go"
GOPRIVATE=""
GOPROXY="https://proxy.golang.org,direct"
GOROOT="/usr/local/Cellar/go/1.13/libexec"
GOSUMDB="sum.golang.org"
GOTMPDIR=""
GOTOOLDIR="/usr/local/Cellar/go/1.13/libexec/pkg/tool/darwin_amd64"
GCCGO="gccgo"
AR="ar"
CC="clang"
CXX="clang++"
CGO_ENABLED="1"
GOMOD="/Users/llimllib/.vim/plugged/govim/go.mod"
CGO_CFLAGS="-g -O2"
CGO_CPPFLAGS=""
CGO_CXXFLAGS="-g -O2"
CGO_FFLAGS="-g -O2"
CGO_LDFLAGS="-g -O2"
PKG_CONFIG="pkg-config"
GOGCCFLAGS="-fPIC -m64 -pthread -fno-caret-diagnostics -Qunused-arguments -fmessage-length=0 -fdebug-prefix-map=/var/folders/r4/mc760j7j6xjdgr5p5hxk_xrw0000gq/T/go-build205812094=/tmp/go-build -gno-record-gcc-switches -fno-common"

</pre></details>

### What version/commit of `govim` are you using?
`93fa47`

### What did you expect to see?

My file in a way that I can edit it

### What did you see instead?

A file that is completely underlined and very difficult to view or edit because of a minor staticcheck warning.

1. Create a file `main.go` with the contents:
```go
package something

import "fmt"

func main() {
	fmt.Printf("hello %s", "world")
}
```
2. enable staticcheck in your config: `call govim#config#Set("Staticcheck", 1)`
3. open `main.go`
4. note that the whole file is now underlined because "at least one file in a package should have a package comment" (which is presumably a staticcheck error that applies to the whole file?)

This effectively renders any file in any package without a package comment to be uneditable when staticcheck is turned on.

I'm pretty sure this is a side effect of 93fa47f0efdf28ea6b948bf241774acbd029d604, cc @leitzler

**Comment by leitzler** [comment]
This is, unfortunately a bug in the version of staticcheck that gopls uses.
It is fixed in staticcheck master, and I think that Dominik plans to release a new version soon (in december). As soon as there is a new version, it can be brought into gopls.

The best workaround I have so far is.. to actually add a comment at the top of one of the files in the package :)
`// Package foo ...`

**Comment by myitcv** [comment]
@leitzler could/should we work around this by requiring a specific version of `staticcheck` in `govim`?

**Comment by leitzler** [comment]
We can, by adding a `replace` directive to `go.mod`. Staticcheck is using release branches without tagging the master branch, so we cannot simply `go get` a newer version.

Should we? Yeah, I think so. The question would then be what version to use instead. 2019.2.3 that is used now is from 4 Sep so there are a bunch of commits to choose among since then, and I don't know where Dominik fixed this particular thing.

**Comment by llimllib** [comment]
Hey I can be helpful! I went on a little code read of staticcheck after our initial discussion, it looks to me like this was the commit that fixed it: https://github.com/dominikh/go-tools/commit/d2b70924fd1a8b2692f7aa058e66f32e1eea4ac7#diff-b5a8127ddd8cc742ee7f751754466b6bR62

**Comment by leitzler** [comment]
Thanks @llimllib! There will be a new release of staticcheck when Go 1.14 is released (because of changes to the export data).

**Comment by leitzler** [comment]
Just an update, staticcheck was just release so now we only need to wait for gopls to upgrade (http://golang.org/cl/220477) before we can upgrade govim.

**Comment by leitzler** [comment]
As https://github.com/govim/govim/pull/789 just was merged, this should be fixed.
Give it a try with master and don't hesitate to re-open it if you still experience the issue!
