### ISSUE TITLE
cmd/govim: add tests to verify that turning off unimported completions works

### ISSUE THREAD

**Issue by myitcv** [govim/govim#687]
Now that https://github.com/govim/govim/commit/d80f0e21c2e3291f93bd60d3d70079f877834d85 has landed with unimported completions turned on by default, we need tests to verify that turning that feature off works.

**Comment by tjcain** [comment]
Hi @myitcv, I would like to take a stab at this if that is ok?

Would it make sense to give this case its own scenario i.e. `govim/cmd/govim/testdata/scenario_completeunimported_off` or make it a case in the existing `scenario_completeunimported`?

**Comment by myitcv** [comment]
Hi @tjcain 

> I would like to take a stab at this if that is ok?

Absolutely fine. 

I've just submitted #793 to complete a bit of house work. So once that is merged please do have a stab at this. https://github.com/govim/govim/wiki/govim-tests should help provide a bit of background, but if you do have any questions please do feel free to ask here or in `#govim-dev` on [Gophers Slack](https://invite.slack.golangbridge.org/)
