### ISSUE TITLE
cmd/govim: Error whilst handling autocommand

### ISSUE THREAD

**Issue by llimllib** [govim/govim#688]
### What version of Vim/Gvim are you using?

<details><summary>Vim/Gvim version</summary><br><pre>
$ vim --version
VIM - Vi IMproved 8.2 (2019 Dec 12, compiled Jan 10 2020 09:03:33)
macOS version
Included patches: 1-109
Compiled by llimllib@nina
Huge version without GUI.  Features included (+) or not (-):
+acl               -farsi             -mouse_sysmouse    -tag_old_static
+arabic            +file_in_path      +mouse_urxvt       -tag_any_white
+autocmd           +find_in_path      +mouse_xterm       -tcl
+autochdir         +float             +multi_byte        +termguicolors
-autoservername    +folding           +multi_lang        +terminal
-balloon_eval      -footer            -mzscheme          +terminfo
+balloon_eval_term +fork()            +netbeans_intg     +termresponse
-browse            -gettext           +num64             +textobjects
++builtin_terms    -hangul_input      +packages          +textprop
+byte_offset       +iconv             +path_extra        +timers
+channel           +insert_expand     -perl              +title
+cindent           +job               +persistent_undo   -toolbar
-clientserver      +jumplist          +popupwin          +user_commands
+clipboard         +keymap            +postscript        +vartabs
+cmdline_compl     +lambda            +printer           +vertsplit
+cmdline_hist      +langmap           +profile           +virtualedit
+cmdline_info      +libcall           -python            +visual
+comments          +linebreak         -python3           +visualextra
+conceal           +lispindent        +quickfix          +viminfo
+cryptv            +listcmds          +reltime           +vreplace
-cscope            +localmap          +rightleft         +wildignore
+cursorbind        -lua               -ruby              +wildmenu
+cursorshape       +menu              +scrollbind        +windows
+dialog_con        +mksession         +signs             +writebackup
+diff              +modify_fname      +smartindent       -X11
+digraphs          +mouse             -sound             -xfontset
-dnd               -mouseshape        +spell             -xim
-ebcdic            +mouse_dec         +startuptime       -xpm
+emacs_tags        -mouse_gpm         +statusline        -xsmp
+eval              -mouse_jsbterm     -sun_workshop      -xterm_clipboard
+ex_extra          +mouse_netterm     +syntax            -xterm_save
+extra_search      +mouse_sgr         +tag_binary        
   system vimrc file: "$VIM/vimrc"
     user vimrc file: "$HOME/.vimrc"
 2nd user vimrc file: "~/.vim/vimrc"
      user exrc file: "$HOME/.exrc"
       defaults file: "$VIMRUNTIME/defaults.vim"
  fall-back for $VIM: "/usr/local/share/vim"
Compilation: gcc -c -I. -Iproto -DHAVE_CONFIG_H   -DMACOS_X -DMACOS_X_DARWIN  -O2   -Wall -U_FORTIFY_SOURCE -D_FORTIFY_SOURCE=1       
Linking: gcc   -L/usr/local/lib -o vim        -lm -lncurses  -liconv -framework AppKit           
</pre></details>

### What version of Go are you using (`go version`)?

<pre>
$ go version
go version go1.13 darwin/amd64
</pre>

### What operating system and processor architecture are you using (`go env`)?

<details><summary><code>go env</code> Output</summary><br><pre>
$ go env
GO111MODULE=""
GOARCH="amd64"
GOBIN="/Users/llimllib/go/bin"
GOCACHE="/Users/llimllib/Library/Caches/go-build"
GOENV="/Users/llimllib/Library/Application Support/go/env"
GOEXE=""
GOFLAGS=""
GOHOSTARCH="amd64"
GOHOSTOS="darwin"
GONOPROXY=""
GONOSUMDB=""
GOOS="darwin"
GOPATH="/Users/llimllib/go"
GOPRIVATE=""
GOPROXY="https://proxy.golang.org,direct"
GOROOT="/usr/local/Cellar/go/1.13/libexec"
GOSUMDB="sum.golang.org"
GOTMPDIR=""
GOTOOLDIR="/usr/local/Cellar/go/1.13/libexec/pkg/tool/darwin_amd64"
GCCGO="gccgo"
AR="ar"
CC="clang"
CXX="clang++"
CGO_ENABLED="1"
GOMOD="/Users/llimllib/code/xo/go.mod"
CGO_CFLAGS="-g -O2"
CGO_CPPFLAGS=""
CGO_CXXFLAGS="-g -O2"
CGO_FFLAGS="-g -O2"
CGO_LDFLAGS="-g -O2"
PKG_CONFIG="pkg-config"
GOGCCFLAGS="-fPIC -m64 -pthread -fno-caret-diagnostics -Qunused-arguments -fmessage-length=0 -fdebug-prefix-map=/var/folders/r4/mc760j7j6xjdgr5p5hxk_xrw0000gq/T/go-build021249064=/tmp/go-build -gno-record-gcc-switches -fno-common"

</pre></details>

### What version/commit of `govim` are you using?

`4208a9805df15a50ba6e714ca806d425351d50bd`

### What is the output of `:messages` in Vim?

see below

### Do the Vim channel, `govim` or `gopls` log files show anything interesting?

The govim log is 380k lines long, so I snipped off the last 620 so that hopefully there's relevant context: https://gist.github.com/llimllib/8e57e7ae5542a693eb21e22ea71d3d0b

There doesn't seem to be anything interesting in the gopls log, but I included the end of the file in that same gist over roughly the same timespan. Same for the vim log.

### How did you install `govim`?

vim-plug

### What did you do?

Nothing that I know of, just writing some go and trying to write my file to disk

### What did you expect to see?

No exception

### What did you see instead?

When I try to save my file, I get an exception. The extremely irritating and dangerous upshot of the exception is that my file does not get written to disk (!). The exception follows:

```
Error detected while processing function <SNR>47_callbackAutoCommand[18]..<SNR>47_ch_evalexpr:
line    4:
E605: Exception not caught: got error whilst handling autocommand:2: driver error: ChannelCall("s:batchCall") failed: failed to call s:batchCall([[[call s:mustBeZero setbufline 1 293 ^I^I^IFunctionName:  indexFunctionName(cols, table.GoNa
me),] [call s:mustBeZero setbufline 1 292 ^I^I^IIsPrimary:     primary,] [call s:mustBeZero setbufline 1 291 ^I^I^IIsUnique:      unique,] [call s:mustBeZero setbufline 1 290 ^I^I^IConditionList: conditions,] [call s:mustBeZero setbufline
 1 289 ^I^I^IColumnArgList: arglist, // These don't have data types! XXX] [call s:mustBeZero setbufline 1 288 ^I^I^IColumnNames:   cols,] [call s:mustBeZero setbufline 1 287 ^I^I^IName:          name,] [call s:mustBeZero setbufline 1 74 ^
IFunctionName string] [call s:mustBeZero deletebufline 1 74 73] [call s:mustBeZero setbufline 1 69 ^IConditionList string] [call s:mustBeZero setbufline 1 64 ^IColumnArgList string] [call s:mustBeZero setbufline 1 59 ^IIsPrimary bool] [ca
ll s:mustBeZero setbufline 1 56 ^IIsUnique bool] [call s:mustBeZero setbufline 1 53 ^IColumnNames [
```

Is there any way that the extension could ensure that the file gets written to disk even if an error occurs during processing?

May be related to #682

**Comment by myitcv** [comment]
Hmm that's a strange error. Because `govim` appears to have failed as it tried to apply the results of a `Formatting` call (which, by default, happens after import fixing on save). 

Are you able to reproduce this per chance? 

Otherwise are you able to share the entire log file in order to reconstruct what happened here?

FWIW: you can always "force" a save to disk by doing:

```
:noau w
```

This will skip any `govim` "hooks" that otherwise trigger on save.

That said, very much appreciate you raising this bug in any case because it's clearly preferable to fix this problems rather than working around them.

> May be related to #682

Possibly, but based on what I've seen above, that looks unlikely.

**Comment by llimllib** [comment]
> This will skip any govim "hooks" that otherwise trigger on save.

neat! thanks for the tip.

I did notice that this reproduced with the file in that particular state, but I unfortunately didn't save it, I really should have, sorry :(

Fortunately I haven't restarted since and my tmp files are still around. I updated the gist with the full govim log

**Comment by llimllib** [comment]
[govim.zip](https://github.com/govim/govim/files/4083452/govim.zip)

Check that, gist doesn't like the file because it's too large. Here's a zip file with the govim log in it, sorry again I didn't save the reproducer

**Comment by myitcv** [comment]
Thanks @llimllib - that's a pretty impressive log file! Reconstructing the state from the log file is going to take some time (to automate), so I'll put that on the back-burner for now: https://github.com/govim/govim/issues/696

In the meantime, if you run into this again, saving the file state when things went wrong would help to short-circuit the investigation. 

Thanks again for following up here so diligently. It might feel like this sorts of issues are small, in amongst the weeds etc. But solving them is critical to improving the stability of `govim` and `gopls`.

**Comment by leitzler** [comment]
It's not a minimal reproducible but should aid in debugging a lot:
```
$ cd $(mktemp -d) && go mod init x
$ cat << EOF | base64 -d > main.go
cGFja2FnZSBtYWluCgppbXBvcnQgKAoJImxvZyIKCSJ0aW1lIgopCgpmdW5jIG1haW4oKSB7CiAg
ICBmb3IgewogICAgdGltZS5TbGVlcCh0aW1lLlNlY29uZCo1KQoKCWxvZy5QcmludGxuKCJIaXN0
b3J5OiIpCglmb3IgXywgaCA6PSByYW5nZSBbXXN0cmluZ3siYSIsImIifSB7CgkJbG9nLlByaW50
ZigiJXMiLGgpCgkJZm9yIGkgOj0gcmFuZ2UgW11pbnR7fSB7CgkJCWxvZy5QcmludGYoIiV2Iixp
KQoJCX0KCX0KfQp9Cgo=
EOF
$ vi main.go
```
.. and then `:w`

**Comment by myitcv** [comment]
#708 has a fixed for the case highlighted by the repro. Let's see how we get on with that.

**Comment by llimllib** [comment]
Thanks for the work! I'll update and reënable govim and report if I see a reproduction (and actually save the reproducer this time ugh...)
