### ISSUE TITLE
cmd/govim: feature Request: fill struct

### ISSUE THREAD

**Issue by frioux** [govim/govim#709]
vim-go had a command called `:GoFillStruct` and it would transform (for example), this:

```go
x := Person{}
```

into

```go
x := Person{
	Name: "",
	Employed: false,
	Age: 0,
}
```

Basically it'd set all the fields to their zero value.  I have no idea how hard this is with the gopls engine but it'd be nice to recover this functionality.

**Comment by myitcv** [comment]
Thanks for raising @frioux.

This is indeed something we would need to push up to `gopls` because type information is required. 

Are you happy filing an issue there? Then we can cross reference from here.

**Comment by frioux** [comment]
yeah I can do that. there being golang/go right?

**Comment by myitcv** [comment]
Yes indeed, e.g. per https://github.com/golang/go/issues/37237 use a `x/tools/gopls:` prefix in the subject.

**Comment by myitcv** [comment]
@frioux kindly raised this as https://github.com/golang/go/issues/37576

**Comment by leitzler** [comment]
Closing as per #885, we now support `GOVIMFillStruct` :tada:
