### ISSUE TITLE
cmd/govim: Issue in running GOVIMGoToDef command

### ISSUE THREAD

**Issue by varun06** [govim/govim#776]
### What version of Vim/Gvim are you using?

<details><summary></summary><br><pre>
$ vim --version

</pre>8.2</details>

### What version of Go are you using (`go version`)?

<pre>
$ go version
go version go1.13.7 darwin/amd64
</pre>

### What operating system and processor architecture are you using (`go env`)?

<details><summary><code>go env</code> Output</summary><br><pre>
$ go env
GO111MODULE=""
GOARCH="amd64"
GOBIN=""
GOCACHE="/Users/varun/Library/Caches/go-build"
GOENV="/Users/varun/Library/Application Support/go/env"
GOEXE=""
GOFLAGS=""
GOHOSTARCH="amd64"
GOHOSTOS="darwin"
GONOPROXY=""
GONOSUMDB=""
GOOS="darwin"
GOPATH="/Users/varun/go"
GOPRIVATE=""
GOPROXY="gocenter.io,proxy.golang.org,direct"
GOROOT="/usr/local/go"
GOSUMDB="off"
GOTMPDIR=""
GOTOOLDIR="/usr/local/go/pkg/tool/darwin_amd64"
GCCGO="gccgo"
AR="ar"
CC="clang"
CXX="clang++"
CGO_ENABLED="1"
GOMOD=""
CGO_CFLAGS="-g -O2"
CGO_CPPFLAGS=""
CGO_CXXFLAGS="-g -O2"
CGO_FFLAGS="-g -O2"
CGO_LDFLAGS="-g -O2"
PKG_CONFIG="pkg-config"
</pre></details>

### What version/commit of `govim` are you using?
v0.0.29

### What is the output of `:messages` in Vim?
```
Error detected while processing function <SNR>63_callbackCommand[3]..<SNR>63_ch_evalexpr:
line    4:
E605: Exception not caught: got error whilst handling command:GOVIMGoToDef: should have a valid buffer number by this point; we don't
3 fewer lines; before #36  13:05:16
1 change; before #35  13:05:14
1 change; before #34  13:05:08
1 change; before #33  13:05:04
1 line less; before #32  13:04:51
"~/go/pkg/mod/<>/lua/lua.go" [New file] --No lines in buffer--
Error detected while processing function <SNR>63_callbackCommand[3]..<SNR>63_ch_evalexpr:
line    4:
E605: Exception not caught: got error whilst handling command:GOVIMGoToDef: should have a valid buffer number by this point; we don't
```

### How did you install `govim`?

vim-plug

### What did you do?
press `gd` on a function name

### What did you expect to see?
File where function is defined opens in a vertical split.

### What did you see instead?
Empty buffer opened and an errror is flashed.

**Comment by leitzler** [comment]
Thanks for the report!
I tried to reproduce it on my mac using `v0.0.29` but didn't manage get the error. Do it happen everytime you use `GOVIMGoToDef`, or are you able to provide a reproducible?

The govim log would be very valuable as well if you are able to attach it, but do note that it contain your code!

**Comment by myitcv** [comment]
If you can also confirm (with a repro if possible) whether this reproduces with a minimal `govim` setup that would also help. i.e. just `govim` loaded.

**Comment by varun06** [comment]
Will report back today. Don’t know if it matters, but I am in a multi
module repository and it fails to open a buffer that’s in an outside
module.

**Comment by myitcv** [comment]
> I am in a multi module repository and it fails to open a buffer that’s in an outside module.

That's it then. At the moment, `govim` only has the ability to define a single workspace root. https://github.com/govim/govim/issues/172 captures how to handle the scenario you're trying to work with.

**Comment by myitcv** [comment]
I'll leave this open for now until you confirm later, but I'm minded to close this in favour of #172. If you use multi-module repos regularly, then feedback on the UI/UX points would be appreciated. It's a relatively tricky problem, but I suspect we might be able to start with something basic.

**Comment by varun06** [comment]
Gotcha, you can close it. I have couple multi module repos that I work with
every day. So happy to help wherever I can.

**Comment by myitcv** [comment]
Thanks. Thinking about what sort of UI/UX you would want/expect would be help. Please comment over in #172
