### ISSUE TITLE
Find interface implementations

### ISSUE THREAD

**Issue by Skarlso** [govim/govim#806]
Hello!

This is more then a question or a feature request really. :)

Is it possible to do a find implementation of interfaces like Goland does it? Is it possible / feasible to implement something like that? That would be massively cool. :)

Cheers!

**Comment by myitcv** [comment]
Hi @Skarlso - you're in luck - see https://github.com/govim/govim/issues/577. As you can see, @tjcain is in the process of taking a look at this. I'll close this given we can track things in #577

**Comment by Skarlso** [comment]
Wooooot! \o/
