### ISSUE TITLE
cmd/govim: error popup when opening non Go file with GO111MODULE=on set

### ISSUE THREAD

**Issue by aitva** [govim/govim#822]
### What version of Vim/Gvim are you using?

<details><summary>Vim/Gvim version</summary><br><pre>
$ vim --version
VIM - Vi IMproved 8.2 (2019 Dec 12, compiled Feb 21 2020 11:35:07)
Included patches: 1-292
Compiled by aitva@ThinkPad-W530
Huge version without GUI.  Features included (+) or not (-):
+acl               -farsi             -mouse_sysmouse    -tag_old_static
+arabic            +file_in_path      +mouse_urxvt       -tag_any_white
+autocmd           +find_in_path      +mouse_xterm       -tcl
+autochdir         +float             +multi_byte        +termguicolors
-autoservername    +folding           +multi_lang        +terminal
-balloon_eval      -footer            -mzscheme          +terminfo
+balloon_eval_term +fork()            +netbeans_intg     +termresponse
-browse            -gettext           +num64             +textobjects
++builtin_terms    -hangul_input      +packages          +textprop
+byte_offset       +iconv             +path_extra        +timers
+channel           +insert_expand     -perl              +title
+cindent           +job               +persistent_undo   -toolbar
+clientserver      +jumplist          +popupwin          +user_commands
+clipboard         +keymap            +postscript        +vartabs
+cmdline_compl     +lambda            +printer           +vertsplit
+cmdline_hist      +langmap           +profile           +virtualedit
+cmdline_info      +libcall           -python            +visual
+comments          +linebreak         -python3           +visualextra
+conceal           +lispindent        +quickfix          +viminfo
+cryptv            +listcmds          +reltime           +vreplace
+cscope            +localmap          +rightleft         +wildignore
+cursorbind        -lua               -ruby              +wildmenu
+cursorshape       +menu              +scrollbind        +windows
+dialog_con        +mksession         +signs             +writebackup
+diff              +modify_fname      +smartindent       +X11
+digraphs          +mouse             -sound             +xfontset
-dnd               -mouseshape        +spell             -xim
-ebcdic            +mouse_dec         +startuptime       +xpm
+emacs_tags        -mouse_gpm         +statusline        +xsmp_interact
+eval              -mouse_jsbterm     -sun_workshop      +xterm_clipboard
+ex_extra          +mouse_netterm     +syntax            -xterm_save
+extra_search      +mouse_sgr         +tag_binary        
   system vimrc file: "$VIM/vimrc"
     user vimrc file: "$HOME/.vimrc"
 2nd user vimrc file: "~/.vim/vimrc"
      user exrc file: "$HOME/.exrc"
       defaults file: "$VIMRUNTIME/defaults.vim"
  fall-back for $VIM: "/usr/local/share/vim"
Compilation: gcc -c -I. -Iproto -DHAVE_CONFIG_H     -g -O2 -U_FORTIFY_SOURCE -D_FORTIFY_SOURCE=1       
Linking: gcc   -L/usr/local/lib -Wl,--as-needed -o vim    -lSM -lICE -lXpm -lXt -lX11 -lXdmcp -lSM -lICE  -lm -ltinfo -lnsl  -ldl           
</pre></details>

### What version of Go are you using (`go version`)?

<pre>
$ go version
go version go1.14 linux/amd64
</pre>

### What operating system and processor architecture are you using (`go env`)?

<details><summary><code>go env</code> Output</summary><br><pre>
$ go env
GO111MODULE="on"
GOARCH="amd64"
GOBIN=""
GOCACHE="/home/aitva/.cache/go-build"
GOENV="/home/aitva/.config/go/env"
GOEXE=""
GOFLAGS=""
GOHOSTARCH="amd64"
GOHOSTOS="linux"
GOINSECURE=""
GONOPROXY="gitlab.com/gryzzlybot/*,gitlab.com/aitva/*"
GONOSUMDB="gitlab.com/gryzzlybot/*,gitlab.com/aitva/*"
GOOS="linux"
GOPATH="/home/aitva/go"
GOPRIVATE="gitlab.com/gryzzlybot/*,gitlab.com/aitva/*"
GOPROXY="https://proxy.golang.org,direct"
GOROOT="/usr/local/go"
GOSUMDB="sum.golang.org"
GOTMPDIR=""
GOTOOLDIR="/usr/local/go/pkg/tool/linux_amd64"
GCCGO="gccgo"
AR="ar"
CC="gcc"
CXX="g++"
CGO_ENABLED="1"
GOMOD="/dev/null"
CGO_CFLAGS="-g -O2"
CGO_CPPFLAGS=""
CGO_CXXFLAGS="-g -O2"
CGO_FFLAGS="-g -O2"
CGO_LDFLAGS="-g -O2"
PKG_CONFIG="pkg-config"
GOGCCFLAGS="-fPIC -m64 -pthread -fmessage-length=0 -fdebug-prefix-map=/tmp/go-build963008084=/tmp/go-build -gno-record-gcc-switches"
</pre></details>

### What version/commit of `govim` are you using?

I am using `govim` at 56e86d726dd3c5c0bf4c983bc8cfb3f117dfb89f

### What is the output of `:messages` in Vim?

```
Messages maintainer: Bram Moolenaar <Bram@vim.org>
"TODO.md" 72L, 2081C
```

### How did you install `govim`?

vim-plug

### What did you do?

Open my `.vimrc` or any non `go` file. It works in a temporary directory:

```
cd $(mktemp -d)
touch blah.txt
vim blah.txt
```

### What did you expect to see?

Vim working without `govim`.

### What did you see instead?

A red popup, telling me that my workspace is misconfigured:

```
 Your workspace is misconfigured: go [-e -json -compiled=true -test=true -export=false -deps=true -find=false -- ./]: exit status 1: go: cannot find main module; see 'go help modules'. Please see https://github.com/golang/tools/blob/master/gopls/doc/troubleshooting.md for more information or file an issue (https://github.com/golang/go/issues/new) if you believe this is a mistake.
```

![image](https://user-images.githubusercontent.com/7271737/76512371-d1510600-6454-11ea-81bb-f37f885e407f.png)

It might be linked to #692

**Comment by myitcv** [comment]
I'm guessing you have `GO111MODULE=on` set?

**Comment by aitva** [comment]
Yes, exactly.

```
$ go env
GO111MODULE="on"
GOARCH="amd64"
GOBIN=""
GOCACHE="/home/aitva/.cache/go-build"
GOENV="/home/aitva/.config/go/env"
GOEXE=""
GOFLAGS=""
GOHOSTARCH="amd64"
GOHOSTOS="linux"
GOINSECURE=""
GONOPROXY="gitlab.com/gryzzlybot/*,gitlab.com/aitva/*"
GONOSUMDB="gitlab.com/gryzzlybot/*,gitlab.com/aitva/*"
GOOS="linux"
GOPATH="/home/aitva/go"
GOPRIVATE="gitlab.com/gryzzlybot/*,gitlab.com/aitva/*"
GOPROXY="https://proxy.golang.org,direct"
GOROOT="/usr/local/go"
GOSUMDB="sum.golang.org"
GOTMPDIR=""
GOTOOLDIR="/usr/local/go/pkg/tool/linux_amd64"
GCCGO="gccgo"
AR="ar"
CC="gcc"
CXX="g++"
CGO_ENABLED="1"
GOMOD="/home/aitva/dev/gryzzly/brain/go.mod"
CGO_CFLAGS="-g -O2"
CGO_CPPFLAGS=""
CGO_CXXFLAGS="-g -O2"
CGO_FFLAGS="-g -O2"
CGO_LDFLAGS="-g -O2"
PKG_CONFIG="pkg-config"
GOGCCFLAGS="-fPIC -m64 -pthread -fmessage-length=0 -fdebug-prefix-map=/tmp/go-build264954714=/tmp/go-build -gno-record-gcc-switches"
```

**Comment by myitcv** [comment]
My immediate suggestion would be to unset `GO111MODULE` (which has the same effect as `GO111MODULE=auto`). Go 1.14 (and 1.13 for that matter) will just "do the right thing" - if that's no an option, please can you explain why?

If you want the history, it's contained in https://github.com/golang/go/issues/35818

The crux of my argument is that Vim/`govim` cannot and therefore should not make any determination about when to start `gopls`. Because to do so would require them to have Go-specific logic, and the same argument would then apply for all editors and plugins. 

In this case, because `GO111MODULE=on`, `gopls` is expecting to find a module and does not (notice that `GOMOD=/dev/null`, which is distinct from the value of `GOMOD=""` when `GO111MODULE` is unset or set to `auto`). Arguably `gopls` should not care unless asked to do something relating to a `.go` (or related) file, but that somewhat butts up against the requirement that `gopls` eagerly load the workspace.

**Comment by aitva** [comment]
Great, thank you ! It fixes the red popup.

Unfortunately, I still have `govim` error while opening non Go files:

```
Error detected while processing function <SNR>19_userBusy[3]..GOVIM_internal_SetUserBusy[2]..<SNR>19_callbackFunction[2]..<SNR>19_ch_evalexpr:
line 4: E605: Exception not caught: got error whilst handling GOVIM_internal_SetUserBusy: failed to get current position: failed to resolve buffer 1
```

![image](https://user-images.githubusercontent.com/7271737/76531870-1df90900-6476-11ea-81aa-661b73676c70.png)

The error does not appear immediately, but after a few seconds.

**Comment by myitcv** [comment]
That's #821 which I'm about to fix. 

If you're happy that we can switch to #821 and close this issue, please do. Thanks for the report in any case.

**Comment by aitva** [comment]
Perfect, I am closing the issue. Thank you for `govim` it is a great project!
