### ISSUE TITLE
cmd/govim: dereferencing completion with completeopt "longest" removes field

### ISSUE THREAD

**Issue by leitzler** [govim/govim#830]
### What version of Vim/Gvim are you using?

<details><summary>Vim/Gvim version</summary><br><pre>
$ vim --version
VIM - Vi IMproved 8.2 (2019 Dec 12, compiled Feb 28 2020 20:23:59)
macOS version
Included patches: 1-327
Compiled by pontus@MacBook-Pro.localdomain
Huge version without GUI.  Features included (+) or not (-):
+acl               -farsi             -mouse_sysmouse    -tag_old_static
+arabic            +file_in_path      +mouse_urxvt       -tag_any_white
+autocmd           +find_in_path      +mouse_xterm       -tcl
+autochdir         +float             +multi_byte        +termguicolors
-autoservername    +folding           +multi_lang        +terminal
-balloon_eval      -footer            -mzscheme          +terminfo
+balloon_eval_term +fork()            +netbeans_intg     +termresponse
-browse            -gettext           +num64             +textobjects
++builtin_terms    -hangul_input      +packages          +textprop
+byte_offset       +iconv             +path_extra        +timers
+channel           +insert_expand     -perl              +title
+cindent           +job               +persistent_undo   -toolbar
-clientserver      +jumplist          +popupwin          +user_commands
+clipboard         +keymap            +postscript        +vartabs
+cmdline_compl     +lambda            +printer           +vertsplit
+cmdline_hist      +langmap           +profile           +virtualedit
+cmdline_info      +libcall           -python            +visual
+comments          +linebreak         -python3           +visualextra
+conceal           +lispindent        +quickfix          +viminfo
+cryptv            +listcmds          +reltime           +vreplace
-cscope            +localmap          +rightleft         +wildignore
+cursorbind        -lua               -ruby              +wildmenu
+cursorshape       +menu              +scrollbind        +windows
+dialog_con        +mksession         +signs             +writebackup
+diff              +modify_fname      +smartindent       -X11
+digraphs          +mouse             -sound             -xfontset
-dnd               -mouseshape        +spell             -xim
-ebcdic            +mouse_dec         +startuptime       -xpm
+emacs_tags        -mouse_gpm         +statusline        -xsmp
+eval              -mouse_jsbterm     -sun_workshop      -xterm_clipboard
+ex_extra          +mouse_netterm     +syntax            -xterm_save
+extra_search      +mouse_sgr         +tag_binary
   system vimrc file: "$VIM/vimrc"
     user vimrc file: "$HOME/.vimrc"
 2nd user vimrc file: "~/.vim/vimrc"
      user exrc file: "$HOME/.exrc"
       defaults file: "$VIMRUNTIME/defaults.vim"
  fall-back for $VIM: "/usr/local/share/vim"
Compilation: gcc -c -I. -Iproto -DHAVE_CONFIG_H   -DMACOS_X -DMACOS_X -DMACOS_X_DARWIN -DMACOS_X -DMACOS_X_DARWIN -DMACOS_X -DMACOS_X_DARWIN  -g -O2 -U_FORTIFY_SOURCE -D_FORTIFY_SOURCE=1
Linking: gcc   -L/usr/local/lib -o vim        -lm -lncurses  -liconv -framework AppKit
</pre></details>

### What version of Go are you using (`go version`)?

<pre>
$ go version
go version go1.14 darwin/amd64
</pre>

### What operating system and processor architecture are you using (`go env`)?

<details><summary><code>go env</code> Output</summary><br><pre>
$ go env
GO111MODULE=""
GOARCH="amd64"
GOBIN=""
GOCACHE="/Users/pontus/Library/Caches/go-build"
GOENV="/Users/pontus/Library/Application Support/go/env"
GOEXE=""
GOFLAGS=""
GOHOSTARCH="amd64"
GOHOSTOS="darwin"
GOINSECURE=""
GONOPROXY=""
GONOSUMDB=""
GOOS="darwin"
GOPATH="/Users/pontus/go"
GOPRIVATE=""
GOPROXY="https://proxy.golang.org,direct"
GOROOT="/usr/local/go"
GOSUMDB="sum.golang.org"
GOTMPDIR=""
GOTOOLDIR="/usr/local/go/pkg/tool/darwin_amd64"
GCCGO="gccgo"
AR="ar"
CC="clang"
CXX="clang++"
CGO_ENABLED="1"
GOMOD=""
CGO_CFLAGS="-g -O2"
CGO_CPPFLAGS=""
CGO_CXXFLAGS="-g -O2"
CGO_FFLAGS="-g -O2"
CGO_LDFLAGS="-g -O2"
PKG_CONFIG="pkg-config"
GOGCCFLAGS="-fPIC -m64 -pthread -fno-caret-diagnostics -Qunused-arguments -fmessage-length=0 -fdebug-prefix-map=/var/folders/xm/ls208xd174v95pgd20rn_qbh0000gn/T/go-build138646951=/tmp/go-build -gno-record-gcc-switches -fno-common"
</pre></details>

### What version/commit of `govim` are you using?
master (4744627)

### What did you do?
In my vimrc I have `set completeopt+=longest` and I use the cursor keys + enter to select item in the completion popup. **_(note: <kbd>Down</kbd>, <kbd>Enter</kbd> instead of <kbd>Ctrl</kbd>+<kbd>n</kbd>, <kbd>Esc</kbd>)_**

When trying to complete a struct field that gopls automatically dereference, the field name itself is removed.

Reproduce by adding the following to `cmd/govim/testdata/scenario_default/`:
```
# Test that ominfunc complete works with completeopt+=longest and dereferences.

vim ex 'e main.go'
vim ex 'set completeopt+=longest'
vim ex 'call cursor(12,1)'
vim ex 'call feedkeys(\"A\\<C-X>\\<C-O>\\<Down>\\<Enter>\", \"xt\")'
vim ex 'w'
cmp main.go main.go.golden

# Assert that we have received no error (Type: 1) or warning (Type: 2) log messages
# Disabled pending resolution to https://github.com/golang/go/issues/34103
# errlogmatch -start -count=0 'LogMessage callback: &protocol\.LogMessageParams\{Type:(1|2), Message:".*'

-- go.mod --
module mod.com

go 1.12
-- main.go --
package main

type foo struct {
	aaa *string
	bbb *string
}

func fn(s string) {}

func main() {
	var x foo
	fn(x.
}
-- main.go.golden --
package main

type foo struct {
	aaa *string
	bbb *string
}

func fn(s string) {}

func main() {
	var x foo
	fn(*x.aaa
}
```

gopls Completion call:
```
gopls server start =======================
gopls.Completion() return; err: <nil>; res:
&protocol.CompletionList{
    IsIncomplete: true,
    Items:        {
        {
            Label:            "*aaa",
            Kind:             5,
            Tags:             nil,
            Detail:           "*string",
            Documentation:    "",
            Deprecated:       false,
            Preselect:        true,
            SortText:         "00000",
            FilterText:       "aaa",
            InsertText:       "",
            InsertTextFormat: 1,
            TextEdit:         &protocol.TextEdit{
                Range: protocol.Range{
                    Start: protocol.Position{Line:11, Character:6},
                    End:   protocol.Position{Line:11, Character:6},
                },
                NewText: "aaa",
            },
            AdditionalTextEdits: {
                {
                    Range: protocol.Range{
                        Start: protocol.Position{Line:11, Character:4},
                        End:   protocol.Position{Line:11, Character:4},
                    },
                    NewText: "*",
                },
            },
            CommitCharacters: nil,
            Command:          (*protocol.Command)(nil),
            Data:             nil,
        },
        {
            Label:            "*bbb",
            Kind:             5,
            Tags:             nil,
            Detail:           "*string",
            Documentation:    "",
            Deprecated:       false,
            Preselect:        false,
            SortText:         "00001",
            FilterText:       "aaa",
            InsertText:       "",
            InsertTextFormat: 1,
            TextEdit:         &protocol.TextEdit{
                Range: protocol.Range{
                    Start: protocol.Position{Line:11, Character:6},
                    End:   protocol.Position{Line:11, Character:6},
                },
                NewText: "bbb",
            },
            AdditionalTextEdits: {
                {
                    Range: protocol.Range{
                        Start: protocol.Position{Line:11, Character:4},
                        End:   protocol.Position{Line:11, Character:4},
                    },
                    NewText: "*",
                },
            },
            CommitCharacters: nil,
            Command:          (*protocol.Command)(nil),
            Data:             nil,
        },
    },
}
gopls server end =======================
```

### What did you expect to see?
Test pass, as completion for fields that aren't dereferenced works as expected.

### What did you see instead?
Test fail

**Comment by myitcv** [comment]
Is this related to https://github.com/vim/vim/issues/5730?

**Comment by leitzler** [comment]
Haven't checked but I don't think this is a vim issue (based on the fact that it works if the string isn't a reference). I.e. if the struct looks like:
```
type foo struct {
    aaa *string
    bbb *string
    ccc string
}
```
and I choose `ccc` in the completion popup it works as expected.

**Comment by leitzler** [comment]
Did some more digging into this and it looks like there is a race for buffer updates in govim.
When selecting an item in the completion popup `vim` sends a `CompleteDone` event, followed by a `BufChange`.

The thing is that our `CompleteDone` handler grabs the contents of the buffer (to apply AdditionalTextEdits), then gets interrupted by the `BufChange`, and finally applies the AdditionalTextEdit effectively overwriting the `BufChange`.

In the following example `gopls` sends me a list of completion items when I trigger the completion. The first item is `*aaa *string` (_**note the the AdditionalTextEdit**_):
```
2020-03-21T20:11:19.110834_#1:         {
2020-03-21T20:11:19.110834_#1:             Label:            "*aaa",
2020-03-21T20:11:19.110834_#1:             Kind:             5,
2020-03-21T20:11:19.110834_#1:             Tags:             nil,
2020-03-21T20:11:19.110834_#1:             Detail:           "*string",
2020-03-21T20:11:19.110834_#1:             Documentation:    "",
2020-03-21T20:11:19.110834_#1:             Deprecated:       false,
2020-03-21T20:11:19.110834_#1:             Preselect:        true,
2020-03-21T20:11:19.110834_#1:             SortText:         "00000",
2020-03-21T20:11:19.110834_#1:             FilterText:       "aaa",
2020-03-21T20:11:19.110834_#1:             InsertText:       "",
2020-03-21T20:11:19.110834_#1:             InsertTextFormat: 1,
2020-03-21T20:11:19.110834_#1:             TextEdit:         &protocol.TextEdit{
2020-03-21T20:11:19.110834_#1:                 Range: protocol.Range{
2020-03-21T20:11:19.110834_#1:                     Start: protocol.Position{Line:12, Character:6},
2020-03-21T20:11:19.110834_#1:                     End:   protocol.Position{Line:12, Character:6},
2020-03-21T20:11:19.110834_#1:                 },
2020-03-21T20:11:19.110834_#1:                 NewText: "aaa",
2020-03-21T20:11:19.110834_#1:             },
2020-03-21T20:11:19.110834_#1:             AdditionalTextEdits: {
2020-03-21T20:11:19.110834_#1:                 {
2020-03-21T20:11:19.110834_#1:                     Range: protocol.Range{
2020-03-21T20:11:19.110834_#1:                         Start: protocol.Position{Line:12, Character:4},
2020-03-21T20:11:19.110834_#1:                         End:   protocol.Position{Line:12, Character:4},
2020-03-21T20:11:19.110834_#1:                     },
2020-03-21T20:11:19.110834_#1:                     NewText: "*",
2020-03-21T20:11:19.110834_#1:                 },
2020-03-21T20:11:19.110834_#1:             },
2020-03-21T20:11:19.110834_#1:             CommitCharacters: nil,
2020-03-21T20:11:19.110834_#1:             Command:          (*protocol.Command)(nil),
2020-03-21T20:11:19.110834_#1:             Data:             nil,
2020-03-21T20:11:19.110834_#1:         },
```

When I select the first completion popup item (using <kbd>Down</kbd>,<kbd>Enter</kbd>) vim triggers a `CompleteDone` event. 
```
2020-03-21T20:18:11.542210_#1: vim start =======================
2020-03-21T20:18:11.542210_#1: recvJSONMsg: [199] ["function","autocommand:5"," govim CompleteDone *.go",[1,{"word":"aaa","menu":"*string","user_data":"govim","info":"","kind":"","abbr":"*aaa"}]]
2020-03-21T20:18:11.542210_#1: vim end =======================
2020-03-21T20:18:11.542335_#1: run: waiting to read a JSON message
2020-03-21T20:18:11.543072_#1: vim start =======================
2020-03-21T20:18:11.543072_#1: sendJSONMsg: [0,[128,"ex","wundo! /var/folders/xm/ls208xd174v95pgd20rn_qbh0000gn/T/1584818291542583000515290700"]]
2020-03-21T20:18:11.543072_#1: vim end =======================
2020-03-21T20:18:11.544738_#1: vim start =======================
2020-03-21T20:18:11.544738_#1: recvJSONMsg: [200] ["callback",128,[""]]
2020-03-21T20:18:11.544738_#1: vim end =======================
2020-03-21T20:18:11.544829_#1: run: waiting to read a JSON message
2020-03-21T20:18:11.544971_#1: vim start =======================
2020-03-21T20:18:11.544971_#1: sendJSONMsg: [0,[129,"expr","\u0026eventignore"]]
2020-03-21T20:18:11.544971_#1: vim end =======================
```

Vim also updates the buffer and sends a `BufChange`:
```
2020-03-21T20:18:11.544993_#1: vim start =======================
2020-03-21T20:18:11.544993_#1: recvJSONMsg: [201] ["function","function:GOVIM_internal_BufChanged",[1,13,14,0,[{"lnum":13,"col":7,"added":0,"end":14,"lines":["\tfn(x.aaa"]},{"lnum":13,"col":8,"added":0,"end":14,"lines":["\tfn(x.aaa"]},{"lnum":13,"col":9,"added":0,"end":14,"lines":["\tfn(x.aaa"]}]]]
2020-03-21T20:18:11.544993_#1: vim end =======================
```

Then, eventually, the `CompleteDone` event finishes:
```
2020-03-21T20:18:11.548800_#1: vim start =======================
2020-03-21T20:18:11.548800_#1: sendJSONMsg: [0,[132,"call","s:batchCall",[["call",["s:mustBeZero",null],"setbufline",1,13,"\tfn(*x."],["call",["s:mustBeZero",null],"listener_flush",1],["expr",["s:mustNoError",null],"join(getbufline(1, 0, \"$\"), \"\\n\").\"\\n\""]]]]
2020-03-21T20:18:11.548800_#1: vim end =======================
```

When the `CompleteDone` request is received we grab the buffer contents to prepare for adding additional text edits (the `*`):
https://github.com/govim/govim/blob/4744627b79bdfb55d9a3abb7c8f466586f65566a/cmd/govim/textedit.go#L29

Then we get interrupted by the `BufChange` event that adds `aaa`:
https://github.com/govim/govim/blob/4744627b79bdfb55d9a3abb7c8f466586f65566a/cmd/govim/buffer_events.go#L129

Finally we apply the additional text edit (`*` in this case) to the line that we fetched before we got interrupted by a `BufChange`. And the `BufChange` addition is gone!

**Comment by leitzler** [comment]
The difference between running with and without `longest` is that when `longest` isn't set, vim adds `aaa` to the buffer immediately when opening the Completion popup.

That way the first buffer fetch in `CompleteDone` will pick up a line that already has `aaa` in it, and that hides the fact the `BufChange` is overwritten.

It can be shown by running without `longest` set, and select `bbb` from the completion popup.

If <kbd>Down</kbd> is used to go to `bbb`, the buffer will still show `aaa`.
If <kbd>Ctrl</kbd>-<kbd>n</kbd> is used, the buffer is also updated to show `bbb`.

Using arrow keys the result will be `fn(*x.aaa` (note, `aaa` instead of the selected `bbb`).

**Comment by leitzler** [comment]
There is a test case in #834 to showcase the issue. As the describe above the main problem isn't related to `longest` at all, just the fact that govim applies additional text edits to a stale buffer.

**Comment by myitcv** [comment]
Noting an observation based on our conversation in Slack last night.

As demonstrated by the test case in #834 (which requires `completeopt-=longest`), Vim is sending a `CompleteDone` event _before_ the delta that represents the completion item having been chosen. This can't be right: hitting enter chooses the completion candidate. This should insert the completion text (which will trigger a delta), _then_ fire `CompleteDone`, at which point we would have the correct buffer state and apply the additional text edit(s) correctly.

This also appears to create an apparent off-by-one error when applying additional text edits with `completeopt+=longest`.

I'll start a discussion in https://groups.google.com/forum/#!forum/vim_dev to ascertain whether this is a Vim bug or whether we need to hook into another event.

**Comment by myitcv** [comment]
See https://github.com/vim/vim/issues/5860#issuecomment-605517595 for more details and a workaround.

**Comment by leitzler** [comment]
Initial issue is solved so I close this. The offset error when applying additional text edits is covered by  #836
