### ISSUE TITLE
govim hangs on update

### ISSUE THREAD

**Issue by ohait** [govim/govim#837]
### What version of Vim/Gvim are you using?
<pre>
VIM - Vi IMproved 8.2 (2019 Dec 12, compiled Mar 27 2020 12:36:15)
Included patches: 1-460
Modified by jonathon.fernyhough@york.ac.uk
Compiled by jonathon.fernyhough@york.ac.uk
Huge version with GTK3 GUI.  Features included (+) or not (-):
+acl               -farsi             -mouse_sysmouse    -tag_old_static
+arabic            +file_in_path      +mouse_urxvt       -tag_any_white
+autocmd           +find_in_path      +mouse_xterm       +tcl
+autochdir         +float             +multi_byte        +termguicolors
-autoservername    +folding           +multi_lang        +terminal
+balloon_eval      -footer            -mzscheme          +terminfo
+balloon_eval_term +fork()            +netbeans_intg     +termresponse
+browse            +gettext           +num64             +textobjects
++builtin_terms    -hangul_input      +packages          +textprop
+byte_offset       +iconv             +path_extra        +timers
+channel           +insert_expand     +perl              +title
+cindent           +job               +persistent_undo   +toolbar
+clientserver      +jumplist          +popupwin          +user_commands
+clipboard         +keymap            +postscript        +vartabs
+cmdline_compl     +lambda            +printer           +vertsplit
+cmdline_hist      +langmap           +profile           +virtualedit
+cmdline_info      +libcall           -python            +visual
+comments          +linebreak         +python3           +visualextra
+conceal           +lispindent        +quickfix          +viminfo
+cryptv            +listcmds          +reltime           +vreplace
+cscope            +localmap          +rightleft         +wildignore
+cursorbind        +lua               +ruby              +wildmenu
+cursorshape       +menu              +scrollbind        +windows
+dialog_con_gui    +mksession         +signs             +writebackup
+diff              +modify_fname      +smartindent       +X11
+digraphs          +mouse             +sound             -xfontset
+dnd               +mouseshape        +spell             +xim
-ebcdic            +mouse_dec         +startuptime       +xpm
+emacs_tags        +mouse_gpm         +statusline        +xsmp_interact
+eval              -mouse_jsbterm     -sun_workshop      +xterm_clipboard
+ex_extra          +mouse_netterm     +syntax            -xterm_save
+extra_search      +mouse_sgr         +tag_binary
   system vimrc file: "$VIM/vimrc"
     user vimrc file: "$HOME/.vimrc"
 2nd user vimrc file: "~/.vim/vimrc"
      user exrc file: "$HOME/.exrc"
  system gvimrc file: "$VIM/gvimrc"
    user gvimrc file: "$HOME/.gvimrc"
2nd user gvimrc file: "~/.vim/gvimrc"
       defaults file: "$VIMRUNTIME/defaults.vim"
    system menu file: "$VIMRUNTIME/menu.vim"
  fall-back for $VIM: "/usr/share/vim"
Compilation: gcc -c -I. -Iproto -DHAVE_CONFIG_H -DFEAT_GUI_GTK  -pthread -I/usr/include/gtk-3.0 -I/usr/include/at-spi2-atk/2.0 -I/usr/include/at-spi-2.0 -I/usr/include/dbus-1.0 -I/usr/lib/x86_64-linux-gnu/dbus-1.0/include -I/usr/include/gtk-3.0 -I/usr/include/gio-unix-2.0/ -I/usr/include/cairo -I/usr/include/pango-1.0 -I/usr/include/harfbuzz -I/usr/include/pango-1.0 -I/usr/include/atk-1.0 -I/usr/include/cairo -I/usr/include/pixman-1 -I/usr/include/freetype2 -I/usr/include/libpng16 -I/usr/include/freetype2 -I/usr/include/libpng16 -I/usr/include/gdk-pixbuf-2.0 -I/usr/include/libpng16 -I/usr/include/glib-2.0 -I/usr/lib/x86_64-linux-gnu/glib-2.0/include -Wdate-time  -g -O2 -fdebug-prefix-map=/build/vim-qOazsc/vim-8.2.0460=. -fstack-protector-strong -Wformat -Werror=format-security -D_REENTRANT -U_FORTIFY_SOURCE -D_FORTIFY_SOURCE=1
Linking: gcc   -L. -Wl,-Bsymbolic-functions -Wl,-z,relro -Wl,-z,now -fstack-protector -rdynamic -Wl,-export-dynamic -Wl,-E  -Wl,-Bsymbolic-functions -Wl,-z,relro -Wl,-z,now -Wl,--as-needed -o vim   -lgtk-3 -lgdk-3 -lpangocairo-1.0 -lpango-1.0 -latk-1.0 -lcairo-gobject -lcairo -lgdk_pixbuf-2.0 -lgio-2.0 -lgobject-2.0 -lglib-2.0 -lSM -lICE -lXpm -lXt -lX11 -lXdmcp -lSM -lICE  -lm -ltinfo -lnsl  -lselinux  -lcanberra -lacl -lattr -lgpm -ldl  -L/usr/lib -llua5.2 -Wl,-E  -fstack-protector-strong -L/usr/local/lib  -L/usr/lib/x86_64-linux-gnu/perl/5.26/CORE -lperl -ldl -lm -lpthread -lcrypt  -L/usr/lib/python3.6/config-3.6m-x86_64-linux-gnu -lpython3.6m -lpthread -ldl -lutil -lm -L/usr/lib/x86_64-linux-gnu -ltcl8.6 -ldl -lz -lpthread -lm -lruby-2.5 -lpthread -lgmp -ldl -lcrypt -lm
</pre>
### What version of Go are you using (`go version`)?
<pre>
go version go1.13.1 linux/amd64
<pre>

### What operating system and processor architecture are you using (`go env`)?

<details><summary><code>go env</code> Output</summary><br><pre>
$ go env
GO111MODULE=""
GOARCH="amd64"
GOHOSTARCH="amd64"
GOHOSTOS="linux"
GOOS="linux"
</pre></details>

### What version/commit of `govim` are you using?
latest via plug

### What is the output of `:messages` in Vim?
hard to reproduce, since the UI hangs

### How did you install `govim`?

vim-plug 

### What did you do?

opening any go file seems to hang on update

it seems like after several seconds it recovers, but then triggers again after the next update.

I run vim with -V/tmp/vim.log and in tail mode i see this when it hangs:
<pre>
autocommand call s:Highlight_Matching_Pair()

Executing CursorMoved Autocommands for "*"
autocommand :call s:userBusy(1)

Executing CursorMoved Autocommands for "*"
autocommand call s:Highlight_Matching_Pair()

Executing CursorMoved Autocommands for "*"
autocommand :
</pre>
cursor is hanging after the colon

**Comment by ohait** [comment]
ignore the vim.log, it stops writing at random positions.
also, i can say everything works fine, it hangs only during update (as long as i'm faster then the update, it doesn't hangs but it completes, navigate and everything else)

**Comment by myitcv** [comment]
Thanks for raising this and sorry you're running into issues.

Please can you explain what you mean by "hangs only during update" - what does "update" mean here? Can you provide the steps you take to repro the hang?

Also, it should be possible to get some `govim` logs out of this:

```
export GOVIM_LOGFILE_TMPL=%v
vim file.go
```

You should then see that `/tmp/govim.log` and `/tmp/vim_channel.log` have been populated. If you're able to share the contents of those files that would be helpful.

**Comment by ohait** [comment]
right, my vim-fu is limited. I believe it hangs when this timeout:
`set updatetime=700`

**Comment by myitcv** [comment]
Ah I see. I'm not able to repro this using `vim-plug` and the [minimal `.vimrc`](https://github.com/govim/govim/blob/c6fbe06c234152012479891d44e7dbcde3f3df32/cmd/govim/config/minimal.vimrc). 

Does it repro for you with a minimal vimrc?

Are you able to share those logs? That will certainly help to shed some light on what's going on.

**Comment by ohait** [comment]
can't repro on minimal vimrc, working on the logs now

**Comment by ohait** [comment]
govim.log:
<pre>
2020-03-31T12:14:22.493952_#1: gopls client start =======================
2020-03-31T12:14:22.493952_#1: LogMessage callback: &protocol.LogMessageParams{Type:3, Message:"2020/03/31 12:14:22 go/packages.Load\n\tsnapshot = 0\n\tq
uery = [./... builtin]\n\tpackages = 23"}
2020-03-31T12:14:22.493952_#1: gopls client end =======================




2020-03-31T12:14:52.147126_#1: vim start =======================
2020-03-31T12:14:52.147126_#1: recvJSONMsg: [40] ["callback",38,[""]]
2020-03-31T12:14:52.147126_#1: vim end =======================
2020-03-31T12:14:52.147282_#1: run: waiting to read a JSON message
2020-03-31T12:14:52.156226_#1: vim start =======================
2020-03-31T12:14:52.156226_#1: recvJSONMsg: [41] ["callback",39,["",1]]
2020-03-31T12:14:52.156226_#1: vim end =======================
2020-03-31T12:14:52.156463_#1: run: waiting to read a JSON message
2020-03-31T12:14:52.156648_#1: vim start =======================
2020-03-31T12:14:52.156648_#1: sendJSONMsg: [0,[40,"call","s:batchCall",[["call",["s:mustBeZero",null],"sign_unplace","govim"]]]]
2020-03-31T12:14:52.156648_#1: vim end =======================
2020-03-31T12:14:52.157200_#1: vim start =======================
2020-03-31T12:14:52.157200_#1: recvJSONMsg: [42] ["function","function:GOVIM_internal_SetUserBusy",[1,{"bufnr":1,"col":2,"line":35}]]
2020-03-31T12:14:52.157200_#1: vim end =======================
2020-03-31T12:14:52.157338_#1: run: waiting to read a JSON message
2020-03-31T12:14:52.157650_#1: vim start =======================
2020-03-31T12:14:52.157650_#1: sendJSONMsg: [42,["",null]]
2020-03-31T12:14:52.157650_#1: vim end =======================
</pre>

**Comment by ohait** [comment]
<pre>
  0.064256 : looking for messages on channels                                                                                                            
  0.064276 on 0: Getting JSON message 0                                                                                                                  
  0.064281 on 0: Invoking channel callback <SNR>13_define                                                                                                
  0.068779 SEND on 0(in): '[39,["function","autocommand:1"," govim BufNewFile,BufRead *.go",[{"Num":1,"Name":"/home/oha/work/midgard/sleipnir-calls-clien
'                                                                                                                                                        
  0.068832 on 0: Blocking read JSON for id 39                                                                                                            
  0.068838 on 0: Waiting for up to 30000 msec                                                                                                            
  0.071781 RECV on 0(out): '[0,[39,"call","listener_add","GOVIM_internal_EnrichDelta",1]]                                                                
'                                                                                                                                                        
  0.071795 on 0: Waiting for up to 30000 msec                                                                                                            
 30.100390 on 0: Timed out on id 39                                                                                                                      
 30.108432 SEND on 0(in): '[40,["callback",38,[""]]]                                                                                                     
'                                                                                                                                                        
 30.116907 : SafeState: back to waiting, triggering SafeStateAgain                                                                                       
 30.117135 : looking for messages on channels                                                                                                            
 30.117158 on 0: Getting JSON message 0                                                                                                                  
 30.117169 on 0: Invoking channel callback <SNR>13_define                                                                                                
 30.117552 SEND on 0(in): '[41,["callback",39,["",1]]]                                                                                                   
'                                                                                                                            
</pre>

**Comment by myitcv** [comment]
Thanks - are you able to share the complete log files as gists? 

https://gist.github.com/

I'll need the full context.

**Comment by ohait** [comment]
not easy, there is lot of data i cannot freely share. I can try to remove them or we can use a private channel?

**Comment by myitcv** [comment]
Yes, very happy for you to send them to me privately: paul@myitcv.io

**Comment by myitcv** [comment]
(or on Gophers Slack: `@myitcv`)

**Comment by myitcv** [comment]
One quick question: please can you add to this issue the full output from `vim --version`?

**Comment by myitcv** [comment]
My bet is that you are running a version `v8.2.0452 <= N < v8.2.0466`

**Comment by ohait** [comment]
added the full version

**Comment by myitcv** [comment]
You have, sadly, run into a Vim bug that was present in the version range mentioned in https://github.com/govim/govim/issues/837#issuecomment-606536824. Context: 

https://groups.google.com/d/msg/vim_dev/AjQA8dE0EpY/miFlLh0PAwAJ

If you upgrade to at least `v8.2.0466` that should fix things. 

In the meantime, I will add a warning/error message to `govim` in case a user tries to run `govim` with a bad version. Apologies for the inconvenience, and thanks again for raising the issue; I should probably have made such a change in the first place.

**Comment by ohait** [comment]
I might have updated vim as well while updating govim, i did run an update on ubuntu but didn't checked the list of changes.

**Comment by myitcv** [comment]
You can revert to a previous version of Vim if that's easier; it's just that you cannot be using a version of Vim in the range `v8.2.0452 <= N < v8.2.0466`
