### ISSUE TITLE
ftplugin/go.vim not being loaded with vim 8 package

### ISSUE THREAD

**Issue by vrischmann** [govim/govim#875]
### What version of Vim/Gvim are you using?

<details><summary>Vim/Gvim version</summary><br><pre>
$ vim --version
VIM - Vi IMproved 8.2 (2019 Dec 12, compiled May 11 2020 00:00:00)
Included patches: 1-735
Modified by <bugzilla@redhat.com>
Compiled by <bugzilla@redhat.com>
Huge version with GTK3 GUI.  Features included (+) or not (-):
+acl               -farsi             +mouse_sgr         +tag_binary
+arabic            +file_in_path      -mouse_sysmouse    -tag_old_static
+autocmd           +find_in_path      +mouse_urxvt       -tag_any_white
+autochdir         +float             +mouse_xterm       -tcl
-autoservername    +folding           +multi_byte        +termguicolors
+balloon_eval      -footer            +multi_lang        +terminal
+balloon_eval_term +fork()            -mzscheme          +terminfo
+browse            +gettext           +netbeans_intg     +termresponse
++builtin_terms    -hangul_input      +num64             +textobjects
+byte_offset       +iconv             +packages          +textprop
+channel           +insert_expand     +path_extra        +timers
+cindent           +ipv6              +perl/dyn          +title
+clientserver      +job               +persistent_undo   +toolbar
+clipboard         +jumplist          +popupwin          +user_commands
+cmdline_compl     +keymap            +postscript        +vartabs
+cmdline_hist      +lambda            +printer           +vertsplit
+cmdline_info      +langmap           +profile           +virtualedit
+comments          +libcall           -python            +visual
+conceal           +linebreak         +python3/dyn       +visualextra
+cryptv            +lispindent        +quickfix          +viminfo
+cscope            +listcmds          +reltime           +vreplace
+cursorbind        +localmap          +rightleft         +wildignore
+cursorshape       +lua/dyn           +ruby/dyn          +wildmenu
+dialog_con_gui    +menu              +scrollbind        +windows
+diff              +mksession         +signs             +writebackup
+digraphs          +modify_fname      +smartindent       +X11
+dnd               +mouse             -sound             -xfontset
-ebcdic            +mouseshape        +spell             +xim
+emacs_tags        +mouse_dec         +startuptime       +xpm
+eval              +mouse_gpm         +statusline        +xsmp_interact
+ex_extra          -mouse_jsbterm     -sun_workshop      +xterm_clipboard
+extra_search      +mouse_netterm     +syntax            -xterm_save
   system vimrc file: "/etc/vimrc"
     user vimrc file: "$HOME/.vimrc"
 2nd user vimrc file: "~/.vim/vimrc"
      user exrc file: "$HOME/.exrc"
  system gvimrc file: "/etc/gvimrc"
    user gvimrc file: "$HOME/.gvimrc"
2nd user gvimrc file: "~/.vim/gvimrc"
       defaults file: "$VIMRUNTIME/defaults.vim"
    system menu file: "$VIMRUNTIME/menu.vim"
  fall-back for $VIM: "/etc"
 f-b for $VIMRUNTIME: "/usr/share/vim/vim82"
Compilation: gcc -c -I. -Iproto -DHAVE_CONFIG_H -DFEAT_GUI_GTK  -I/usr/include/gtk-3.0 -I/usr/include/pango-1.0 -I/usr/include/glib-2.0 -I/usr/lib64/glib-2.0/include -I/usr/include/harfbuzz -I/usr/include/fribidi -I/usr/include/freetype2 -I/usr/include/libpng16 -I/usr/include/cairo -I/usr/include/pixman-1 -I/usr/include/gdk-pixbuf-2.0 -I/usr/include/libmount -I/usr/include/blkid -I/usr/include/gio-unix-2.0 -I/usr/include/atk-1.0 -I/usr/include/at-spi2-atk/2.0 -I/usr/include/dbus-1.0 -I/usr/lib64/dbus-1.0/include -I/usr/include/at-spi-2.0 -pthread    -O2 -g -pipe -Wall -Werror=format-security -Wp,-D_GLIBCXX_ASSERTIONS -fexceptions -fstack-protector-strong -grecord-gcc-switches -specs=/usr/lib/rpm/redhat/redhat-hardened-cc1 -specs=/usr/lib/rpm/redhat/redhat-annobin-cc1 -m64 -mtune=generic -fasynchronous-unwind-tables -fstack-clash-protection -fcf-protection -D_GNU_SOURCE -D_FILE_OFFSET_BITS=64 -U_FORTIFY_SOURCE -D_FORTIFY_SOURCE=1
Linking: gcc   -L. -Wl,-z,relro  -Wl,-z,now -specs=/usr/lib/rpm/redhat/redhat-hardened-ld -fstack-protector-strong -rdynamic -Wl,-export-dynamic -Wl,--enable-new-dtags -Wl,-z,relro -Wl,-z,now -specs=/usr/lib/rpm/redhat/redhat-hardened-ld  -Wl,-z,relro  -Wl,-z,now -specs=/usr/lib/rpm/redhat/redhat-hardened-ld -lpython3.8 -lcrypt -lpthread -ldl  -lutil -lm -lm  -L/usr/local/lib -Wl,--as-needed -o vim   -lgtk-3 -lgdk-3 -lpangocairo-1.0 -lpango-1.0 -lharfbuzz -latk-1.0 -lcairo-gobject -lcairo -lgdk_pixbuf-2.0 -lgio-2.0 -lgobject-2.0 -lglib-2.0  -lSM -lICE -lXpm -lXt -lX11 -lSM -lICE  -lm  -lselinux  -lncurses -lacl -lattr -lgpm -ldl   -Wl,--enable-new-dtags -Wl,-z,relro -Wl,--as-needed -Wl,-z,now -specs=/usr/lib/rpm/redhat/redhat-hardened-ld -Wl,-z,relro -Wl,--as-needed -Wl,-z,now -specs=/usr/lib/rpm/redhat/redhat-hardened-ld -fstack-protector-strong -L/usr/local/lib  -L/usr/lib64/perl5/CORE -lperl -lpthread -lresolv -ldl -lm -lcrypt -lutil -lc
</pre></details>

### What version of Go are you using (`go version`)?

<pre>
$ go version
go version go1.14 linux/amd64
</pre>

### What operating system and processor architecture are you using (`go env`)?

<details><summary><code>go env</code> Output</summary><br><pre>
$ go env
GO111MODULE=""
GOARCH="amd64"
GOBIN=""
GOCACHE="/home/vincent/.cache/go-build"
GOENV="/home/vincent/.config/go/env"
GOEXE=""
GOFLAGS="-mod=mod"
GOHOSTARCH="amd64"
GOHOSTOS="linux"
GOINSECURE=""
GONOPROXY=""
GONOSUMDB=""
GOOS="linux"
GOPATH="/home/vincent/dev/go"
GOPRIVATE=""
GOPROXY="direct"
GOROOT="/usr/local/go"
GOSUMDB="sum.golang.org"
GOTMPDIR=""
GOTOOLDIR="/usr/local/go/pkg/tool/linux_amd64"
GCCGO="gccgo"
AR="ar"
CC="gcc"
CXX="g++"
CGO_ENABLED="1"
GOMOD=""
CGO_CFLAGS="-g -O2"
CGO_CPPFLAGS=""
CGO_CXXFLAGS="-g -O2"
CGO_FFLAGS="-g -O2"
CGO_LDFLAGS="-g -O2"
PKG_CONFIG="pkg-config"
GOGCCFLAGS="-fPIC -m64 -pthread -fmessage-length=0 -fdebug-prefix-map=/tmp/go-build105158384=/tmp/go-build -gno-record-gcc-switches"
</pre></details>

### What version/commit of `govim` are you using?

8c4bca5906595372d6afd4b97abe5b5fc272de9c

### What is the output of `:messages` in Vim?

```E764: Option 'omnifunc' is not set```

### How did you install `govim`?

Vim 8 package

### What did you do?

I have a file `$HOME/.vim/after/ftplugin/go.vim` with this content in it:
```
setl ts=4 sw=4 noexpandtab

packadd govim

call govim#config#Set("FormatOnSave", "gofmt")
call govim#config#Set("Staticcheck", 1)
call govim#config#Set("CompleteUnimported", 0)

nmap <Leader>gi :GOVIMGoImports<cr>
nmap <Leader>re :GOVIMRename<cr>
nmap <Leader>h :call GOVIMHover()<cr>
```

The goal is to only load govim when editing a Go file, so to do this I cloned govim in the directory `.vim/pack/plugins/opt/govim`.

However since 8dbe91b51f661a37ecdb77853452016ce154422f this no longer works because as can be seen with `:scriptnames` the [ftplugin/go.vim](https://github.com/govim/govim/blob/master/ftplugin/go.vim) file is not loaded:
```
 35: /usr/share/vim/vim82/ftplugin/go.vim
 36: ~/.vim/after/ftplugin/go.vim
 37: ~/.vim/pack/plugins/opt/govim/plugin/govim.vim
 38: ~/.vim/pack/plugins/opt/govim/ftdetect/go.vim
 39: ~/.vim/pack/plugins/opt/govim/autoload/govim/config.vim
 40: /usr/share/vim/vim82/indent/go.vim
```

compare this to the output of `:scriptnames` with 6b50ea78deda52e516ea171693fa2db3bb66514b:
```
 36: ~/.vim/after/ftplugin/go.vim
 37: ~/.vim/pack/plugins/opt/govim/plugin/govim.vim
 38: ~/.vim/pack/plugins/opt/govim/ftdetect/go.vim
 39: ~/.vim/pack/plugins/opt/govim/autoload/govim/config.vim
 40: /usr/share/vim/vim82/indent/go.vim
 41: /usr/share/vim/vim82/syntax/syntax.vim
 42: /usr/share/vim/vim82/syntax/synload.vim
 43: /usr/share/vim/vim82/syntax/syncolor.vim
 44: /usr/share/vim/vim82/syntax/go.vim
 ...
 50: ~/.vim/pack/plugins/opt/govim/ftplugin/go.vim
```

Since that file is not loaded anymore, completion is not set up properly and fails with this error:
```E764: Option 'omnifunc' is not set```

I can workaround this issue but I'm wondering if I'm doing something wrong with my vim setup (having my own ftplugin/go.vim calling `packadd govim`) or if it's a bug.

**Comment by myitcv** [comment]
Thanks for raising the issue @vrischmann and apologies for the break here.

The change in 8dbe91b is, I think, the right thing to do. Previously we were triggered all `BufRead` and `FileType` autocommands to fire when `govim` completed loading (the loading of an external plugin like `govim` is async and certain things need to happen when that event happens). Firing all autocommands has other side effects that are potentially uncontrollable (other plugins that have registered `BufRead` or `FileType` autocommands) fire again when they are not expecting to.

Following 8dbe91b, I think the the issue here is that you are loading `govim` in the `after/ftplugin` for Go. So the `ftplugin` part of the plugin never gets loaded (that phase has already completed).

> The goal is to only load govim when editing a Go file

Can you explain the rationale behind this? Is it that you want to avoid the cost of `govim` and `gopls` instances? 

FWIW I have ~20 Vim instances open at any given point. I'm now using the new `-remote` capability of `gopls` to share a single remote instance of `gopls`, with a simple forwarded instance used by each `govim`.

So in my `.vimrc` I have the following (could be set as an environment variable):

```
let $GOVIM_GOPLS_FLAGS="-remote=auto -remote.listen.timeout=0"
```

For more details on the various options see https://github.com/golang/tools/blob/master/gopls/doc/daemon.md

**Comment by vrischmann** [comment]
I can't quite remember but I think I did this for two reasons:
* avoid running govim and gopls for every vim instance I'm running
* avoid defining my Go specific stuff with `au FileType go ...`

I had this in my `.vimrc` before:

```
" Golang
au FileType go set ts=4 sw=4 noexpandtab
au FileType go packadd govim
au FileType go call govim#config#Set("FormatOnSave", "gofmt")
au FileType go call govim#config#Set("Staticcheck", 1)
au FileType go nmap <Leader>gi :GOVIMGoImports<cr>
au FileType go nmap <Leader>dt :GOVIMGoToDef<cr>
au FileType go nmap <Leader>dv :GOVIMGoToDef vsplit<cr>
au FileType go nmap <Leader>b :GOVIMQuickfixDiagnostics<cr>
au FileType go nmap <Leader>r :GOVIMReferences<cr>
au FileType go nmap <Leader>e :GOVIMRename<cr>
au FileType go nmap <Leader>h :call GOVIMHover()<cr>
```

and I liked the ability to just stuff anything go related into the file `after/ftplugin/go.vim`. But it's not really a big deal, I can go back to using `au FileType go` (or maybe there's a better way for this, I'll do some research).

I didn't know about the remote capability, I'll take a look.

I'll close this issue then since this is not a bug but my Vim setup which is wrong.
Thanks for your help !
