### ISSUE TITLE
Feature Req: Display variables with same scope

### ISSUE THREAD

**Issue by stmuk** [govim/govim#894]
There was a useful feature present in vim-go where I could select a variable and it would highlight all instances of that variable within the same scope.  

I found this particularly useful in spotting scope issues and  variable shadowing with "err".  

I believe this functionality is available from gopls since I had it working in vim-go using gopls.

**Comment by stmuk** [comment]
D'uh govim behaves like this all ready with about 5 secs delay.

**Comment by myitcv** [comment]
Indeed - and that time is configurable via this config setting:

https://github.com/govim/govim/blob/e2a1802131f331832d667736aa27f023636f0c3a/cmd/govim/config/minimal.vimrc#L29

**Comment by leitzler** [comment]
I'm quite sure I follow, there is a feature in `govim` that highlights references using gopls automatically, unless you have it disabled in your vimrc:
```
call govim#config#Set("HighlightReferences", 0)
```

[![asciicast](https://asciinema.org/a/wjszIH9sPMnCSNCm9gMP3TbY1.svg)](https://asciinema.org/a/wjszIH9sPMnCSNCm9gMP3TbY1)

You can also alter the style of the highlight by setting the highlight group `GOVIMReferences` in your vimrc, e.g.:
```
highlight GOVIMReferences ctermfg=white ctermbg=blue cterm=NONE
```

Do this match what you are looking for?

**Comment by leitzler** [comment]
Ha, note to self - refresh before responding!
