### ISSUE TITLE
cmd/govim: send didChangeWatchedFiles notifications for go.sum files

### ISSUE THREAD

**Issue by stamblerre** [govim/govim#961]
I recently broke (and will soon fix...) the `scenario_modreadonly/script-config_set_env_goflags_mod_readonly` test.
While debugging this, I noticed that `govim` wasn't sending `didChangeWatchedFiles` notifications for `go.sum` files, which is required with `-mod=readonly` (otherwise, the Go command may fail with "updates to go.sum needed").

**Comment by myitcv** [comment]
Ah nice catch, thank you!

**Comment by myitcv** [comment]
Raised https://github.com/govim/govim/pull/966
