### ISSUE TITLE
cmd/govim: don't emit an unbounded amount of logs to /tmp

### ISSUE THREAD

**Issue by cespare** [govim/govim#964]
It would be good if govim could trim or rotate the logs it emits. Or maybe it should only log if it's explicitly turned on.

I've found the logs useful, but I have to watch out for them filling up my disk. Some of my machines have pretty limited space on that partition and the govim logs can really add up. On this machine right now:

```
$ du -c --si /tmp/vim_channel* /tmp/govim_* /tmp/gopls_* | tail -1
1.4G    total
```

If we want to rotate, one simple approach would be: when we create a log named foo-{date}...log., delete all but the newest N files (sorted lexically by name) with the same naming scheme. One problem with that would be that you don't want to delete a log that's in use; you could have a very old session and then a bunch of newer ones have come and gone since then. I suppose a fix for *that* might be to flock each log file when you create it and then flock a log file (with `LOCK_NB`) that you want to delete. That would be a simple way to know that the file is still in use.

Or maybe there's a better way to approach the problem overall.

**Comment by myitcv** [comment]
The decision to log so verbosely stems from the early days of `govim` (and `gopls`). At the time, both were relatively unstable. We thankfully find ourselves today in a much better world. So I 100% agree the logs as the currently stand are not fit for purpose.

Rotating log files is one option. Another is to distinguish the different "levels" of logging. To my mind we always want to log errors (from `gopls`). Whilst errors will already be returned to the user, having explicit logging for them (in addition to `gopls`' standard error output) is useful so the sequence of events is clear. It could therefore become a config option to turn on `"debug"` logging. 

That would mean we have two logging levels:

* error logging only (`"error"`)
* full logging (`"debug"`)

Thoughts?

**Comment by myitcv** [comment]
@cespare please see https://github.com/govim/govim/pull/1064
