### ISSUE TITLE
cmd/govim: add new ToggleReferencesHighlights command

### ISSUE THREAD

**Issue by cespare** [govim/govim#965]
I trigger reference highlights manually (with a shortcut bound to `:GOVIMHighlightReferences`) and right now to clear the highlights I have to use a different command (`:GOVIMClearReferencesHighlights`). (Or I can select a part of the text that's not an identifier and run my highlight command again, as a hacky workaround.)

I propose to add a new command `:GOVIMToggleReferencesHighlights` which will swap back and forth between highlighted and not-highlighted. It looks like a trivial change so I can send a PR if that sounds good.

BTW I don't know if we can change the names but it would be nice to make them consistent.

* `HighlightReferences` -- "highlight" is a verb, "references" is a plural noun, okay. Name seems good.
* `ClearReferencesHighlights` -- now the verb is "clear" and we're using "highlights" as a noun, which is inconsistent. "Reference" is an attributive noun here, so that it ought to be singular (`ClearReferenceHighlights`).

Ideally we'd use the same noun/verb structure: `AddReferenceHighlights`, `ClearReferenceHighlights`, `ToggleReferenceHighlights`.

The second best renaming option would be to accept the verb inconsistency but at least fix the plural "references": `HighlightReferences`, `ClearReferenceHighlights`, `ToggleReferenceHighlights`.

**Comment by myitcv** [comment]
cc @leitzler - I seem to remember stumbling over this naming at the time!

Regarding `ToggleReferenceHighlights` - I'd certainly wouldn't be averse to this. I personally have different key strokes for turning on reference highlights (`<Leader>j`) and turning them off (`<Ctrl-n>`, which also clears any highlights from a `/`-initiated search).

**Comment by cespare** [comment]
> I personally have different key strokes for turning on reference highlights (`<Leader>j`) and turning them off (`<Ctrl-n>`, which also clears any highlights from a `/`-initiated search).

Ooh, I like this. I also have a `:noh` shortcut and it's the first thing I tried to clear the highlights, but of course it didn't work. Upgrading that shortcut is a nice way to clear the highlights. I think I'll just go with that.
