### ISSUE TITLE
Start gopls via `gopls serve`

### ISSUE THREAD

**Issue by stamblerre** [govim/govim#967]
We are trying to improve the `gopls` CLI experience by not defaulting to starting the server when a user runs just `gopls` on the command-line ([golang/go#41282](https://github.com/golang/go/issues/41282)). `gopls` already has a `gopls serve` command which can be used instead. We're asking all language client owners to switch to starting `gopls` via `gopls serve`. There's no rush on this, but just wanted to file an issue to get the process started.

Thanks!

**Comment by myitcv** [comment]
Thanks for raising this, @stamblerre. 

We originally made this change in https://github.com/govim/govim/commit/ca39b23b25bb57a5c591c3fe14b5299373b9d96c, but that got reverted in https://github.com/govim/govim/commit/e539edf7ec0a663dc41d2e4bf3a75c290cafc83a. 

@leitzler will remember the context I'm sure.

**Comment by myitcv** [comment]
From a very vague memory, there was some issue with `serve` and remote usage, but as I said above, @leitzler will remember 😄

**Comment by leitzler** [comment]
Yes, we need to update how we pass flags to `gopls`. Currently `govim` looks at `GOVIM_GOPLS_FLAGS` and append them to `gopls` execution. But if I want to add `-remote` or `-ocagent` that isn't a part of `serve` the command will fail.

(see https://github.com/govim/govim/pull/898#issuecomment-653936668)

It would be nice if `govim` didn't have to keep track of where flags belong (i.e. global or serve).

**Comment by stamblerre** [comment]
Agreed - this is definitely an issue. I may have filed this prematurely--we will try to resolve the issue of the flag ordering before moving forward with https://github.com/golang/go/issues/41282. https://github.com/golang/go/issues/41860 tracks fixing the flag ordering issue.

**Comment by stamblerre** [comment]
Sorry for the noise on this, but we've decided not to change the default in the end. Closing this--sorry about the inconvenience.
