### ISSUE TITLE
cmd/govim: TestScripts/scenario_default/codelens_gc_details is failing at gopls HEAD

### ISSUE THREAD

**Issue by findleyr** [govim/govim#978]
Our govim CI detected the following failure in TestScripts/scenario_default/codelens_gc_details:

https://source.cloud.google.com/results/invocations/0bf3def6-f09a-4a0c-bcdf-ee0662bb456e/targets/golang%2Ftools%2Fgcp_ubuntu%2Fcontinuous-govim/log

Presumably this is due to the command name change to `gopls.gc_details`.  Probably this test should be either disabled or modified to extract the actual codelens command value.

**Comment by leitzler** [comment]
Let me know if it still fails @findleyr, should be fixed now!

**Comment by findleyr** [comment]
Thanks for the quick fix! Our CI is now passing.
